openapi: 3.0.3
info:
  title: A4-DPU-Commissioning API
  version: 1.0.0
  description: API for DPU Commissioning
  contact:
    email: DL_Berlinium@telekom.de
#SECURITY--------------------------------------------------------------------------------------------------
security:
  - OAuth2:
      - giga:cga:all-area-access
paths:
  /resource-order-resource-inventory/v1/commissioningDpuA4Tasks:
    post:
      security:
        - OAuth2:
            - 'rori:commissioningDpuA4Tasks:post'
            - 'giga:cga:all-area-access'
      tags:
        - commissioningDpuA4Tasks
      operationId: commissioningDpuA4Tasks
      description: Installation of DPU Network Element with Network Element Ports and one Network Element Link
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommissioningDpuA4Task'
      responses:
        "201":
          description: success of commissioningDpuA4Task
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NetworkElement"
        "400":
          description: commissioningDpuA4Tasks - Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: commissioningDpuA4Tasks - Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    CommissioningDpuA4Task:
      required:
        - dpuEndSz
        - dpuSerialNumber
        - dpuMaterialNumber
        - dpuKlsId
        - dpuFiberOnLocationId
        - oltEndSz
        - oltPonPort
      type: object
      properties:
        dpuEndSz:
          $ref: '#/components/schemas/AllowedCharacters'
        dpuSerialNumber:
          $ref: '#/components/schemas/AllowedCharacters'
        dpuMaterialNumber:
          $ref: '#/components/schemas/AllowedCharacters'
        dpuKlsId:
          $ref: '#/components/schemas/AllowedCharacters'
        dpuFiberOnLocationId:
          $ref: '#/components/schemas/AllowedCharacters'
        oltEndSz:
          $ref: '#/components/schemas/AllowedCharacters'
        oltPonPort:
          $ref: '#/components/schemas/AllowedUuidCharacters'
      description: Task object
    NetworkElement:
      title: NetworkElement
      type: object
      properties:
        uuid:
          type: string
          description: UUID of this Network Element item
          pattern: '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}'
        creationTime:
          type: string
          description: Timestamp in UTC when this Network Element item was created.
            Automatically filled when creating a new Network Element item
          format: date-time
        description:
          type: string
          description: attributes of this Network Element item
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        lastUpdateTime:
          type: string
          description: Timestamp in UTC when this Network Element item was last updated.
            Automatically updated when updating a Network Element item
          format: date-time
        specificationVersion:
          type: string
          description: specificationVersion of a Network Element
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        address:
          type: string
          description: Address of this Network Element item
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        administrativeState:
          type: string
          description: Administrative State of this Network Element item. Must contain
            one valid state value
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        fsz:
          type: string
          description: FSZ of this Network Element item. Must be unique in combination
            with VPSZ
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        vpsz:
          type: string
          description: VPSZ of this Network Element item. Must be unique in combination
            with FSZ
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        klsId:
          type: string
          description: KLS-ID of this Network Element item
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        lifecycleState:
          type: string
          description: Lifecycle State of this Network Element item. Must contain
            one valid state value
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        operationalState:
          type: string
          description: Operational State of this Network Element item. Must contain
            one valid state value
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        plannedMatNumber:
          type: string
          description: planned material number of this Network Element item
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        plannedRackId:
          type: string
          description: Planned Rack ID of this Network Element item
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        plannedRackPosition:
          type: string
          description: Planned Rack Position of this Network Element item
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        planningDeviceName:
          type: string
          description: Planning Device Name of this Network Element item
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        roles:
          type: string
          description: Roles of this Network Element item. Must contain one valid
            role value XX
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        type:
          type: string
          description: Type of this Network Element item. Must contain one valid type
            value
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        category:
          type: string
          description: NE-Category for filtering the NetworkElements
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        ztpIdent:
          type: string
          description: ZTP-Ident of this Network Element item
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        networkElementGroupUuid:
          type: string
          description: UUID of Network Element Group item to which this Network Element
            item belongs. Must contain UUID of an existing Network Element Group
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        partyId:
          type: string
          description: Party ID of entity to which network elements belongs to
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        fiberOnLocationId:
          type: string
          description: fiberOnLocationId of this Network Element item
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        href:
          type: string
          description: References to NetworkElementGroup
      description: Network Elements are one of several element types of A4 resources.
        Needed for communication between A4 resource inventory and resource inventory
        service.
    AllowedCharacters:
      title: AllowedCharacters
      pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
      type: string
      description: Validator for AllowedCharacters
    AllowedUuidCharacters:
      title: AllowedUuidCharacters
      pattern: '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}'
      type: string
      description: Validator for AllowedUuidCharacters
    Error:
      type: object
      properties:
        code:
          type: string
          description: the code of the Fehlerbildnummer
        reason:
          type: string
          description: Text that explains the reason for error. This can be shown
            to a client user.
          example: Http Error
        message:
          type: string
          description: Text that provide more details and corrective actions related
            to the error. This can be shown to a client user.
          example: Please check your request
      description: Error model from the TMF OpenAPI
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://rhsso-develop.magic.telekom.de/auth/realms/GigabitHub/protocol/openid-connect/token'
          scopes:
            'giga:cga:all-area-access': General Access Scope
            'rori:commissioningDpuA4Tasks:post': POST Scope
