---
swagger: "2.0"
info:
  description: "PSL-Adapter API"
  version: "1.2.0"
  title: "PSL-Adapter"
host: "localhost:8196"
tags:
  - name: "EquipmentController"
  - name: "PslAdapterSessionCallbackController"
  - name: "SessionController"
schemes:
  - "http"
paths:
  /psl-adapter/v1/device/endsz:
    get:
      tags:
        - "EquipmentController"
      summary: "Return PSL device"
      description: ""
      operationId: "getPslDevice"
      parameters:
        - name: "endsz"
          in: "query"
          description: "EndSz of Device"
          required: true
          type: "string"
          pattern: "[0-9]{1,6}\\/[0-9]{1,6}\\/[0-9]{1,6}\\/[a-zA-Z0-9]{2,4}"
          x-example: "*49/8571/0/76HA; 49/8571/0/76H5; 49/8571/0/76H1; 49/8571/0/76H2*"
      responses:
        200:
          description: "PSL data successful delivered"
          schema:
            $ref: "#/definitions/PslDevice"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorResponse"
        404:
          description: "Entity not found"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /psl-adapter/v1/device/session:
    get:
      tags:
        - "EquipmentController"
      summary: "Return PSL device"
      description: ""
      operationId: "getPslDeviceBySession"
      parameters:
        - name: "SessionID"
          in: "query"
          description: "SessionID"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "PSL data successful delivered"
          schema:
            $ref: "#/definitions/PslDevice"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorResponse"
        404:
          description: "Entity not found"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /psl-adapter/v1/equipment/add:
    post:
      tags:
        - "EquipmentController"
      summary: "Add new Psl Eqipment"
      description: ""
      operationId: "createNewEquipment"
      parameters:
        - name: "endsz"
          in: "query"
          description: "EndSz of Device"
          required: true
          type: "string"
          pattern: "[0-9]{1,6}\\/[0-9]{1,6}\\/[0-9]{1,6}\\/[a-zA-Z0-9]{2,4}"
          x-example: "*49/8571/0/76HA; 49/8571/0/76H5; 49/8571/0/76H1; 49/8571/0/76H2*"
        - in: "body"
          name: "body"
          description: "List of Psl Equipment"
          required: true
          schema:
            type: "array"
            items:
              $ref: "#/definitions/PslEquipment"
      responses:
        200:
          description: "PSL data successful added"
          schema:
            $ref: "#/definitions/PslDevice"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /psl-adapter/v1/equipment/endsz:
    get:
      tags:
        - "EquipmentController"
      summary: "Return PSL data from repository"
      description: ""
      operationId: "getPslEquipmentByEndsz"
      parameters:
        - name: "endsz"
          in: "query"
          description: "EndSz of Device"
          required: true
          type: "string"
          pattern: "[0-9]{1,6}\\/[0-9]{1,6}\\/[0-9]{1,6}\\/[a-zA-Z0-9]{2,4}"
          x-example: "*49/8571/0/76HA; 49/8571/0/76H5; 49/8571/0/76H1; 49/8571/0/76H2*"
      responses:
        200:
          description: "PSL data successful delivered"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/PslEquipmentDto"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorResponse"
        404:
          description: "Entity not found"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /psl-adapter/v1/equipment/session:
    get:
      tags:
        - "EquipmentController"
      summary: "Return PSL data from repository"
      description: ""
      operationId: "getPslEquipmentBySessionId"
      parameters:
        - name: "SessionID"
          in: "query"
          description: "SessionID"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "PSL data successful delivered"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/PslEquipmentDto"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorResponse"
        404:
          description: "Entity not found"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /psl-adapter/v1/session:
    post:
      tags:
        - "SessionController"
      summary: "Start import session for PSL data"
      description: ""
      operationId: "startSession"
      parameters:
        - name: "endsz"
          in: "query"
          description: "EndSz of Device"
          required: true
          type: "string"
          pattern: "[0-9]{1,6}\\/[0-9]{1,6}\\/[0-9]{1,6}\\/[a-zA-Z0-9]{2,4}"
          x-example: "*49/8571/0/76HA; 49/8571/0/76H5; 49/8571/0/76H1; 49/8571/0/76H2*"
        - name: "X-Callback-Correlation-Id"
          in: "header"
          description: "Correlation Id"
          required: false
          type: "string"
          format: "uuid"
        - name: "X-Callback-Url"
          in: "header"
          description: "Callback url"
          required: false
          type: "string"
        - name: "X-Callback-Method"
          in: "header"
          description: "Callback http method"
          required: false
          type: "string"
      responses:
        200:
          description: "Import PSL data request successful send"
          schema:
            $ref: "#/definitions/PslSessionDto"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      tags:
        - "SessionController"
      summary: "Check TTL for PSL session and delete when expired"
      description: ""
      operationId: "cleanup"
      parameters: []
      responses:
        200:
          description: "Delete expired PSL session successful"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /psl-adapter/v1/session/cancel:
    put:
      tags:
        - "SessionController"
      summary: "Cancel running import PSL session"
      description: ""
      operationId: "cancel"
      parameters:
        - name: "endsz"
          in: "query"
          description: "EndSz of Device"
          required: true
          type: "string"
          pattern: "[0-9]{1,6}\\/[0-9]{1,6}\\/[0-9]{1,6}\\/[a-zA-Z0-9]{2,4}"
          x-example: "*49/8571/0/76HA; 49/8571/0/76H5; 49/8571/0/76H1; 49/8571/0/76H2*"
      responses:
        200:
          description: "Import PSL session canceled"
          schema:
            $ref: "#/definitions/PslSessionDto"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorResponse"
        404:
          description: "Entity not found"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /psl-adapter/v1/session/cancelById:
    put:
      tags:
        - "SessionController"
      summary: "Cancel running import PSL session by SessionId"
      description: ""
      operationId: "cancelById"
      parameters:
        - name: "sessionId"
          in: "query"
          description: "Id of PSL session"
          required: true
          type: "integer"
          format: "int64"
          x-example: 1000
      responses:
        200:
          description: "Import PSL session canceled"
          schema:
            $ref: "#/definitions/PslSessionDto"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorResponse"
        404:
          description: "Entity not found"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /psl-adapter/v1/session/correlationId:
    get:
      tags:
        - "SessionController"
      summary: "Return import PSL session by CorrelationId"
      description: ""
      operationId: "getSessionByCorrelationId"
      parameters:
        - name: "correlationId"
          in: "query"
          description: "Correlation ID"
          required: true
          type: "string"
          format: "uuid"
      responses:
        200:
          description: "Import PSL session successful delivered"
          schema:
            $ref: "#/definitions/PslSessionDto"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorResponse"
        404:
          description: "Entity not found"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /psl-adapter/v1/session/endsz:
    get:
      tags:
        - "SessionController"
      summary: "Return all import PSL sessions by EndSz"
      description: ""
      operationId: "getSessionByEndsz"
      parameters:
        - name: "endsz"
          in: "query"
          description: "EndSz of Device"
          required: true
          type: "string"
          pattern: "[0-9]{1,6}\\/[0-9]{1,6}\\/[0-9]{1,6}\\/[a-zA-Z0-9]{2,4}"
          x-example: "*49/8571/0/76HA; 49/8571/0/76H5; 49/8571/0/76H1; 49/8571/0/76H2*"
      responses:
        200:
          description: "Import PSL session status successful delivered"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/PslSessionDto"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorResponse"
        404:
          description: "Entity not found"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /psl-adapter/v1/session/id:
    get:
      tags:
        - "SessionController"
      summary: "Return import PSL session by ID"
      description: ""
      operationId: "getSessionById"
      parameters:
        - name: "id"
          in: "query"
          description: "Session ID"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "Import PSL session successful delivered"
          schema:
            $ref: "#/definitions/PslSessionDto"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorResponse"
        404:
          description: "Entity not found"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /psl-adapter/v1/session/timeout:
    put:
      tags:
        - "SessionController"
      summary: "Check import PSL session timeout and cancel when expired"
      description: ""
      operationId: "checkTimeout"
      parameters: []
      responses:
        200:
          description: "Check import PSL session timeout successful"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /pslCallback/session:
    post:
      tags:
        - "PslAdapterSessionCallbackController"
      summary: "PSL session callback"
      description: ""
      operationId: "sessionCallback"
      parameters:
        - name: "X-Callback-Correlation-Id"
          in: "header"
          description: "Value for identifying a single transaction across multiple services\
          \ up to the backend. Usually set by the originating consumer"
          required: true
          type: "string"
          format: "uuid"
        - in: "body"
          name: "body"
          description: "Result of discovery device"
          required: true
          schema:
            $ref: "#/definitions/SessionResponseHolder"
      responses:
        200:
          description: "Psl session done"
      x-async-responses:
        reference-operation-id: "startSession"
definitions:
  CallbackError:
    type: "object"
    properties:
      message:
        type: "string"
      status:
        type: "integer"
        format: "int32"
      code:
        type: "string"
  ErrorResponse:
    type: "object"
    properties:
      errorCode:
        type: "string"
        description: "Error code"
      message:
        type: "string"
        description: "Message"
    description: "Error response of 4xx and 5xx http statuses"
  PslDevice:
    type: "object"
    properties:
      equipmentNummer:
        type: "string"
      materialNummer:
        type: "string"
      klsId:
        type: "string"
      endsz:
        type: "string"
      seriennummer:
        type: "string"
      datumAufbau:
        type: "string"
      gebaeude:
        type: "string"
      raum:
        type: "string"
      reihe:
        type: "string"
      platz:
        type: "string"
      asb:
        type: "string"
      auftragNummer:
        type: "string"
      technischerPlatznummer:
        type: "string"
      pslModules:
        type: "array"
        items:
          $ref: "#/definitions/PslModule"
      sfpModules:
        type: "array"
        items:
          $ref: "#/definitions/SfpModule"
  PslEquipment:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      sessionId:
        type: "integer"
        format: "int64"
      equipmentNummer:
        type: "string"
      materialNummer:
        type: "string"
      headEquipmentNummer:
        type: "string"
      positionEquipmentNummer:
        type: "string"
      positionEquipmentEbene:
        type: "string"
      equipmentArt:
        type: "string"
      klsId:
        type: "string"
      endsz:
        type: "string"
      seriennummer:
        type: "string"
      datumAufbau:
        type: "string"
      gebaeude:
        type: "string"
      raum:
        type: "string"
      reihe:
        type: "string"
      platz:
        type: "string"
      asb:
        type: "string"
      auftragNummer:
        type: "string"
      technischerPlatznummer:
        type: "string"
  PslEquipmentDto:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      equnr:
        type: "string"
      submt:
        type: "string"
      hequi:
        type: "string"
      heqnr:
        type: "string"
      anzEbenen:
        type: "string"
      eqart:
        type: "string"
      adrId:
        type: "string"
      endsz:
        type: "string"
      serge:
        type: "string"
      solldat:
        type: "string"
      gebaeude:
        type: "string"
      raum:
        type: "string"
      reihe:
        type: "string"
      platz:
        type: "string"
      asb:
        type: "string"
      auftragNummer:
        type: "string"
      technischerPlatznummer:
        type: "string"
      sessionId:
        type: "integer"
        format: "int64"
  PslModule:
    type: "object"
    properties:
      slot:
        type: "string"
      equipmentNummer:
        type: "string"
      materialNummer:
        type: "string"
      seriennummer:
        type: "string"
      datumAufbau:
        type: "string"
      auftragNummer:
        type: "string"
      technischerPlatznummer:
        type: "string"
  PslSessionDto:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      endsz:
        type: "string"
      correlationId:
        type: "string"
      startdate:
        type: "string"
        format: "date-time"
      enddate:
        type: "string"
        format: "date-time"
      message:
        type: "string"
      status:
        type: "string"
      xcallbackUrl:
        type: "string"
      xcallbackCorrelationId:
        type: "string"
      xcallbackMethod:
        type: "string"
  SessionResponseHolder:
    type: "object"
    properties:
      error:
        description: "Result of fail operation."
        $ref: "#/definitions/CallbackError"
      response:
        description: "Result of successful operation."
        $ref: "#/definitions/SessionResult"
      success:
        type: "boolean"
    description: "result of PSL data session"
  SessionResult:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      endsz:
        type: "string"
      startdate:
        type: "string"
        format: "date-time"
      enddate:
        type: "string"
        format: "date-time"
  SfpModule:
    type: "object"
    properties:
      slot:
        type: "string"
      port:
        type: "string"
      equipmentNummer:
        type: "string"
      materialNummer:
        type: "string"
      seriennummer:
        type: "string"
      datumAufbau:
        type: "string"
      auftragNummer:
        type: "string"
      technischerPlatznummer:
        type: "string"
