openapi: 3.0.1
info:
  title: Access line switching
  description: |-
    ## Access line switching API

    Microservice which is implementing switching process of access line logical resources for PON Network Switching.
  version: 1.0.0
servers:
  - url: http://localhost:8098/
tags:
  - name: FillDatabase
paths:
  /api/test/v1/fill-access-line-switching-database:
    get:
      tags:
        - FillDatabase
      summary: Fills access line switching database
      description: Launches a script that fills access lines switching database
      operationId: fillDatabase
      parameters:
        - name: END_SZ
          in: query
          description: Target endsz, default values is 49/30/179/76H1
          schema:
            pattern: '[0-9]{1,6}\/[0-9]{1,6}\/[0-9]{1,6}\/[a-zA-Z0-9]{2,4}'
            type: string
        - name: SLOT_NUMBER1
          in: query
          description: Target slot, default values is 3
          schema:
            type: string
        - name: SLOT_NUMBER2
          in: query
          description: Target slot, default values is 4
          schema:
            type: string
      responses:
        200:
          description: ""
          content: {}
    delete:
      tags:
        - FillDatabase
      summary: Clears access line switching database
      description: Launches a script that clears access lines switching database
      operationId: clearDatabase
      responses:
        200:
          description: ""
          content: {}