openapi: 3.0.1
info:
  title: A4 Trigger resource-order-orchestrator Task API
  description: This YAML describes a Service to trigger Tasks to process Resourceorders
    in A4.
  contact:
    name: Team Berlinium
    url: https://gard.telekom.de/gardwiki/display/DGHB/Fulfillment+-+A10NSP+interface
    email: DL_Berlinium@telekom.de
  version: 1.0.0
servers:
  - url: /
#SECURITY--------------------------------------------------------------------------------------------------
security:
  - OAuth2:
      - giga:cga:all-area-access
tags:
  - name: ResourceOrderOrchestratorService
    description: This service provides a functionality to trigger process Resourceorders in A4.
paths:
  /resouresource-order-resource-inventory/v1/a4ResourceOrder:
    post:
      security:
        - OAuth2:
            - 'rori:a4ResourceOrder:post'
            - 'giga:cga:all-area-access'
      tags:
        - ResourceOrderOrchestratorService
      summary: Triggers a RessourceOrder
      description: Triggers a RessourceOrder Process by UUID of the relevant Object
      operationId: a4ResourceOrder
      requestBody:
        description: UUID of the ResourceOrder which has to be processed
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/A4ResourceOrder'
        required: true
      responses:
        201:
          description: trigger request successful created
          content: {}
        400:
          description: post to ResourceOrderOrchestratorService - Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        403:
          description: post to ResourceOrderOrchestratorService - Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: post to ResourceOrderOrchestratorService - Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-codegen-request-body-name: UUID

components:
  schemas:
    A4ResourceOrder:
      required:
        - uuid
      type: object
      properties:
        uuid:
          pattern: '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}'
          type: string
          description: UUID of the entity (RessourceOrder)
    Error:
      type: object
      properties:
        code:
          type: string
          description: Fehlerbildnummer
        reason:
          type: string
          description: Text that explains the reason for error. This can be shown
            to a client user.
          example: Http Error
        message:
          type: string
          description: Text that provide more details and corrective actions related
            to the error. This can be shown to a client user.
          example: Please check your request
      description: Error model from the TMF OpenAPI
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://rhsso-develop.magic.telekom.de/auth/realms/GigabitHub/protocol/openid-connect/token'
          scopes:
            'giga:cga:all-area-access': General Access Scope
            'rori:a4ResourceOrder:post': POST Scope
