swagger: "2.0"
info:
  description: "Description of Interface between DigiOSS and REBELL"
  version: "0_95"
  title: "DigiOSS - REBELL Interface"
  contact:
    email: "stefan.schoenhofen@t-systems.com"
host: "10.171.143.172:9458"
basePath: "/resource-order-resource-inventory"
tags:
- name: "Uewege"
  description: "Information about Uewege in REBELL"
schemes:
- "https"
paths:
  /v1/uewege/{id}:
    get:
      tags:
      - "Uewege"
      summary: "Get one Ueweg with the unique id"
      description: "Find one Ueweg with his id"
      operationId: "findUewegById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "The id of a Ueweg"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
              $ref: "#/definitions/Ueweg"
        400:
          description: Request with given parameter is not correct
          schema:
              $ref: "#/definitions/Error"
        401:
          description: AuthenticationError
          schema:
              $ref: "#/definitions/Error"
        404:
          description: Ueweg not found with given parameter
          schema:
              $ref: "#/definitions/Error"
        500:
          description: Internal Error
          schema:
              $ref: "#/definitions/Error"
  /v1/uewege:
    get:
      tags:
      - "Uewege"
      summary: "Find Uewege by UewegId or Endsz"
      description: "Find Uewege by providing an Endsz or an UewegID. It can Result in more than one Ueweg-Objekt, because of different Versions"
      operationId: "findUewege"
      produces:
      - "application/json"
      parameters:
      - name: "endsz"
        in: "query"
        description: "The Endsz of EndA or EndB of a Ueweg object. This parameter is incompatibel with parameter uewegId"
        required: false
        type: "string"
      - name: "uewegId"
        in: "query"
        description: "The UewegId of a Ueweg object. This parameter is incompatibel with parameter endsz"
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Ueweg"
        400:
          description: Request with given parameter is not correct
          schema:
              $ref: "#/definitions/Error"
        401:
          description: AuthenticationError
          schema:
              $ref: "#/definitions/Error"
        403:
          description: Forbidden, FSZ as part of Endsz is not released
          schema:
              $ref: "#/definitions/Error"
        404:
          description: Ueweg not found with given parameter
          schema:
              $ref: "#/definitions/Error"
        500:
          description: Internal Error
          schema:
              $ref: "#/definitions/Error"

definitions:
  Ueweg:
    type: "object"
    properties:
      id:
        type: integer
        example: 108407614
        description: unique ID of this ueweg
      versionId:
        type: string
        example: 102/1/4601/5154735
        description: Ironman GlobalObjectId
      version:
        type: string
        example: 2
        description: Ironman version id 
      lsz:
        type: string
        example: 4N2
        description: Leitungsschluesselzahl, ueweg type
        minLength: 2
        maxLength: 4
      lszErg:
        type: string
        minLength: 1
        maxLength: 5
        description: lsz additonal
        example: A4CH
      ordNr:
        type: string
        example: 1001
        description: consecutive number
        minLength: 1
        maxLength: 10
      uewegId:
        type: "string"
        example: "I123456789, R123456789"
        description: Ueweg Name in REBELL
        minLength: 10
        maxLength: 10
      status:
        type: "string"
        example: "InBetrieb, geprueft, geprueftZ, deaktiviert"
        description: lifecycle status of the ueweg
      pluralId:
        type: "string"
        description: Ueweg Name in Plural
        minLength: 1
        maxLength: 9
      endPointA:
        $ref: "#/definitions/Endpoint"
      endPointB:
        $ref: "#/definitions/Endpoint"
      validFrom:
        $ref: "#/definitions/DateTime"
      validUntil:
        $ref: "#/definitions/DateTime"
    xml:
      name: "Ueweg"
  EndSz:
    type: object
    properties:
      akz:
        type: string
        example: 49
        description: number for country
      nkz:
        type: string
        example: 651
        description: number for local area
      vkz:
        type: string
        example: 1
        description: number for property
      fsz:
        type: string
        example: 7Y01
        description: number for node
  Endpoint:
    type: object
    properties:
      endSz:
        type: string
        description: akz_nkz_vkz_fsz
      endSzParts:
        $ref: "#/definitions/EndSz"
      deviceHostName:
        type: string
        description: hostname of the device
      portPosition:
        type: string
        description: Slotnumber of device
      portName:
        type: string
        description: name of the port
      vendorPortName:
        type: string
        description: name of the PhysicalConnectionPoint
  DateTime:
    type: string
    example: 22.02.2016 00:00:00
  Error:
    type: "object"
    properties:
      code:
        type: string
        description: an application-specific error code, expressed as a string value
      status:
        type: string
        description: the HTTP status code applicable to this problem, expressed as a string value
      title:
        type: string
        description:  a short, human-readable summary of the problem
      detail:
        type: string
        description: a human-readable explanation specific to this occurrence of the problem
externalDocs:
  description: "Find out more about REBELL"
  url: "http://rebell-ironman.telekom.de/"