openapi: 3.0.1
info:
  title: Access 4.0 access line preprovisioning
  description: '## Access 4.0 access line preprovisioning API'
  version: 1.11.0
servers:
  - url: 'http://localhost:8291/'
tags:
  - name: PreProvisioningProcessExternal
paths:
  /resource-order-resource-inventory/v1/a4/deprovisioning/accessLine:
    post:
      tags:
        - DeprovisioningProcess
      summary: A4 access line deprovisioning process
      description: Starts WG access deprovisioning process for A4 access line
      operationId: startA4AccessLineDeprovisioning
      security:
        - apmToken: []
        - OAuth2:
            - 'rori:provisioningProcess:write'
            - 'giga:request:full'
            - 'giga:cga:all-area-access'
      parameters:
        - $ref: '#/components/parameters/X-Callback-Id'
        - $ref: '#/components/parameters/X-Callback-Correlation-Id-Required'
        - $ref: '#/components/parameters/X-Callback-Url-Required'
        - $ref: '#/components/parameters/X-Callback-Error-Url'
        - $ref: '#/components/parameters/X-Callback-Method'
      requestBody:
        description: A4 Access line info
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/A4AccessLineRequestDto'
        required: true
      responses:
        202:
          description: Process started
        400:
          description: Bad request
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        500:
          description: Can't perform operation
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      callbacks:
        ErrorCallback:
          $ref: '#/components/callbacks/ErrorCallback'
        DeprovisioningCallback:
          $ref: '#/components/callbacks/A4DeprovisioningCallback'
  /callback/wgA4Provisioning/v1/deprovisioning/{uuid}:
    post:
      tags:
        - callback
      summary: A4 access line deprovisioning callback
      description: Sends to a consumer a notification with result of WG a4 access deprovisioning. Provided endpoint from Berlinium.
      operationId: callbackDeprovisioningWithUuid
      security:
        - OAuth2:
            - 'giga:callback:full'
            - 'giga:cga:all-area-access'
            - 'rori:actAccCallback:post'
      parameters:
        - name: uuid
          in: path
          description: UUID of the Generic Resource item
          required: true
          schema:
            $ref: '#/components/schemas/AllowedUuidCharacters'
        - $ref: '#/components/parameters/X-Callback-Correlation-Id-Required'
      requestBody:
        description: Result
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeprovisioningResponseHolder'
        required: true
      responses:
        200:
          description: Deprovisioning process has finished
          content: { }
        400:
          description: Bad request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-async-responses:
        reference-operation-id: startA4AccessLineDeprovisioning
      x-codegen-request-body-name: body
  /callback/wgA4Provisioning/v1/deprovisioning/error/{uuid}:
    post:
      tags:
        - callback
      summary: Endpoint to receive error from 3scale in case of technical failure
      description: Receives error from 3scale in case of technical failure. The endpoint
        is used only for unexpected errors which could not be processed by the provider
        itself. Like HTTP 404 Not Found, HTTP 503 Service Unavailable. Provided endpoint from Berlinium.
      operationId: receiveDeprovisioningErrorWithUuid
      security:
        - OAuth2:
            - 'giga:callback:full'
            - 'giga:cga:all-area-access'
            - 'rori:actAccCallback:post'
      parameters:
        - name: uuid
          in: path
          description: UUID of the Generic Resource item
          required: true
          schema:
            $ref: '#/components/schemas/AllowedUuidCharacters'
        - $ref: '#/components/parameters/X-Callback-Correlation-Id-Required'
        - $ref: '#/components/parameters/X-Callback-Request-Id'
        - $ref: '#/components/parameters/X-Callback-Error-Id'
        - $ref: '#/components/parameters/X-Callback-Error-HTTP-Code'
      requestBody:
        content:
          '*/*':
            schema:
              type: object
        required: false
      responses:
        202:
          description: Your callback API implementation should return this HTTP status
            code if the data was received successfully
          content: { }
      x-codegen-request-body-name: body
  /resource-order-resource-inventory/v1/a4/accessLines:
    post:
      tags:
        - PreProvisioningProcessExternal
      summary: A4 access line provisioning process
      description: Starts WG a4 provisioning process for access line
      operationId: startAccessLinePreProvisioning
      security:
        - apmToken: []
        - OAuth2:
            - 'rori:provisioningProcess:write'
            - 'giga:cga:all-area-access'
      requestBody:
        description: Termination point reference info
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TpRefDto'
        required: true
      responses:
        '201':
          description: Process started
          content: {}
        '400':
          description: Bad request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Can't perform operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  securitySchemes:
    apmToken:
      type: apiKey
      in: header
      name: apm-principal-token
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://rhsso-develop.magic.telekom.de/auth/realms/GigabitHub/protocol/openid-connect/token'
          scopes:
            'rori:provisioningProcess:write': Write scope
            'giga:callback:full': Full scope
            'giga:request:full': Full scope
            'giga:cga:all-area-access': General access scope
  schemas:
    AllowedUuidCharacters:
      title: AllowedUuidCharacters
      pattern: '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}'
      type: string
      description: Validator for AllowedUuidCharacters
    DeprovisioningResponseHolder:
      type: object
      properties:
        error:
          $ref: '#/components/schemas/CallbackError'
        response:
          type: object
          properties: { }
          description: Result of successful operation.
        success:
          type: boolean
      description: Deprovisioning response
    A4AccessLineRequestDto:
      required:
        - lineId
      type: object
      properties:
        lineId:
          pattern: '[A-Z0-9]{3}\.[A-Z0-9]{1,6}\.[A-Z0-9]{1,10}'
          type: string
    CallbackError:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
          format: int32
        code:
          type: string
    ProblemDetails:
      required:
        - title
        - type
      type: object
      properties:
        type:
          type: string
          description: type
        title:
          type: string
          description: title
        status:
          type: integer
          description: status
          format: int32
        detail:
          type: string
          description: detail
        instance:
          type: string
          description: instance
        embedded:
          $ref: '#/components/schemas/SpecificProblemDetails'
      description: Error response of 4xx and 5xx http statuses.
    SpecificProblemDetails:
      required:
        - code
        - reason
      type: object
      properties:
        code:
          type: string
          description: code
        reason:
          type: string
          description: reason
        message:
          type: string
          description: message
        status:
          type: integer
          description: status
          format: int32
      description: Specific problem details(including fehlerbuildnummer code).
    TpRefDto:
      required:
        - endSz
        - klsId
        - partyId
        - portNumber
        - tpRef
      type: object
      properties:
        endSz:
          pattern: '[0-9]{1,6}\/[0-9]{1,6}\/[0-9]{1,6}\/[a-zA-Z0-9]{2,4}'
          type: string
          description: A4 device endSz
        slotNumber:
          maxLength: 50
          minLength: 0
          type: string
          description: A4 device slot number
        portNumber:
          type: string
          description: A4 device port number
        klsId:
          pattern: '[0-9]{1,12}'
          type: string
          description: KlsId of A4 device
        tpRef:
          type: string
          description: Termination point reference
        partyId:
          type: integer
          description: PartyId of termination point
          format: int64
        tpType:
          type: string
          enum:
            - G_FAST_TP
            - PON_TP
  callbacks:
    ErrorCallback:
      '{$request.header.X-Callback-Error-Url}':
        post:
          summary: Endpoint to receive error from 3scale in case of technical failure
          description: Receives error from 3scale in case of technical failure. The endpoint
            is used only for unexpected errors which could not be processed by the provider
            itself. Like HTTP 404 Not Found, HTTP 503 Service Unavailable.
          security:
            - OAuth2:
                - 'giga:callback:full'
                - 'giga:cga:all-area-access'
          parameters:
            - name: uuid
              in: path
              description: UUID of the Generic Resource item
              required: true
              schema:
                $ref: '#/components/schemas/AllowedUuidCharacters'
            - $ref: '#/components/parameters/X-Callback-Correlation-Id-Required'
            - $ref: '#/components/parameters/X-Callback-Request-Id'
            - $ref: '#/components/parameters/X-Callback-Error-Id'
            - $ref: '#/components/parameters/X-Callback-Error-HTTP-Code'
          requestBody:
            content:
              '*/*':
                schema:
                  type: object
            required: false
          responses:
            202:
              description: Your callback API implementation should return this HTTP status
                code if the data was received successfully
              content: { }
    A4DeprovisioningCallback:
      '{$request.header#/X-Callback-Url}':
        post:
          summary: WG A4 access deprovisioning callback
          description: Sends to a consumer a notification with result of WG A4 access deprovisioning.
          security:
            - OAuth2:
                - 'giga:callback:full'
                - 'giga:cga:all-area-access'
          parameters:
            - name: uuid
              in: path
              description: UUID of the Generic Resource item
              required: true
              schema:
                $ref: '#/components/schemas/AllowedUuidCharacters'
            - $ref: '#/components/parameters/X-Callback-Correlation-Id-Required'
          requestBody:
            description: A4 Access Line deprovisioning result
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/DeprovisioningResponseHolder'
            required: true
          responses:
            200:
              description: WG A4 access deprovisioning  is processed
              content: { }
            400:
              description: Bad request
              content:
                '*/*':
                  schema:
                    $ref: '#/components/schemas/ProblemDetails'
  parameters:
    X-Callback-Correlation-Id:
      name: X-Callback-Correlation-Id
      in: header
      description: -|
        UUID V4 generated identifier. Needs to be unique for each request
        overall all systems. With this the callback URL is identified internally.
        If not provided in request it will be generated by the integration layer
        and will be returned in response. The asynchronous callback will provide
        this ID for correlation of request and callback.
      schema:
        type: string
        format: uuid
    X-Callback-Correlation-Id-Required:
      name: X-Callback-Correlation-Id
      in: header
      description: -|
        UUID V4 generated identifier. Needs to be unique for each request
        overall all systems. With this the callback URL is identified internally.
        If not provided in request it will be generated by the integration layer
        and will be returned in response. The asynchronous callback will provide
        this ID for correlation of request and callback.
      required: true
      schema:
        type: string
        format: uuid
    X-Callback-Request-Id:
      name: X-Callback-Request-Id
      in: header
      description: Unique consumerID from request.
      required: true
      schema:
        type: string
        format: uuid
    X-Callback-Error-Id:
      name: X-Callback-Error-Id
      in: header
      description: UUID V4 generated error identifier.
      required: true
      schema:
        type: string
        format: uuid
    X-Callback-Error-HTTP-Code:
      name: X-Callback-Error-HTTP-Code
      in: header
      description: Http error code such as 404, 503.
      required: true
      schema:
        type: string
    X-Callback-Id:
      name: X-Callback-Id
      in: header
      description: Unique consumerID used to identify the request consumer within
        FUSE and provide support for maintenance.
      schema:
        type: string
    X-Callback-Url:
      name: X-Callback-Url
      in: header
      description: The provided Rest Interface from the consumer where the expected
        callback is sent to.
      schema:
        type: string
    X-Callback-Url-Required:
      name: X-Callback-Url
      in: header
      description: The provided Rest Interface from the consumer where the expected
        callback is sent to.
      required: true
      schema:
        type: string
    X-Callback-Error-Url:
      name: X-Callback-Error-Url
      in: header
      description: On 3Scale or provider errors FUSE will try to deliver an error
        on Error Callback URL to the Consumer.
      schema:
        type: string
    X-Callback-Method:
      name: X-Callback-Method
      in: header
      description: Default method if not specified is POST.
      schema:
        type: string
