---
swagger: "2.0"
info:
  description: "A Service which is responsible for Commissioning Process for a DPU\
    \ Device."
  version: "1.2.0"
  title: "DPU Commissioning API"
host: "localhost:8080"
tags:
- name: "DPU Commissioning"
schemes:
- "http"
paths:
  /api/dpucommissioning/v1/dpu/commissioning:
    post:
      tags:
      - "DPU Commissioning"
      summary: "Starts DPU commissioning process"
      description: "Starts commissioning process for DPU device"
      operationId: "startDpuDeviceCommissioning"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "startDpuCommissioningRequest"
        description: "StartDpuCommissioningRequest"
        required: true
        schema:
          $ref: "#/definitions/StartDpuCommissioningRequest"
      - name: "X-Business-Context"
        in: "header"
        description: "https://gard.telekom.de/gardwiki/display/DGHB/X-Business-Context"
        required: false
        type: "string"
      - name: "X-B3-TraceId"
        in: "header"
        description: "https://gard.telekom.de/gardwiki/display/DGHB/X-B3-TraceId"
        required: true
        type: "string"
      - name: "X-B3-SpanId"
        in: "header"
        description: "https://gard.telekom.de/gardwiki/display/DGHB/X-B3-SpanId"
        required: true
        type: "string"
      - name: "X-B3-ParentSpanId"
        in: "header"
        description: "https://gard.telekom.de/gardwiki/display/DGHB/X-B3-ParentSpanId"
        required: false
        type: "string"
      responses:
        201:
          description: "Process started"
          schema:
            $ref: "#/definitions/DpuCommissioningResponse"
          headers:
            X-Business-Context:
              type: "string"
              description: "https://gard.telekom.de/gardwiki/display/DGHB/X-Business-Context"
        400:
          description: "Bad request"
          headers:
            X-Business-Context:
              type: "string"
              description: "https://gard.telekom.de/gardwiki/display/DGHB/X-Business-Context"
        500:
          description: "Can't perform operation"
          headers:
            X-Business-Context:
              type: "string"
              description: "https://gard.telekom.de/gardwiki/display/DGHB/X-Business-Context"
  /api/dpucommissioning/v1/dpu/decommissioning:
    post:
      tags:
      - "DPU Commissioning"
      summary: "Starts DPU decommissioning process"
      description: "Starts decommissioning process for DPU device"
      operationId: "startDpuDeviceDecommissioning"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "startDpuDecommissioningRequest"
        description: "StartDpuDecommissioningRequest"
        required: true
        schema:
          $ref: "#/definitions/StartDpuDecommissioningRequest"
      - name: "X-Business-Context"
        in: "header"
        description: "https://gard.telekom.de/gardwiki/display/DGHB/X-Business-Context"
        required: false
        type: "string"
      - name: "X-B3-TraceId"
        in: "header"
        description: "https://gard.telekom.de/gardwiki/display/DGHB/X-B3-TraceId"
        required: true
        type: "string"
      - name: "X-B3-SpanId"
        in: "header"
        description: "https://gard.telekom.de/gardwiki/display/DGHB/X-B3-SpanId"
        required: true
        type: "string"
      - name: "X-B3-ParentSpanId"
        in: "header"
        description: "https://gard.telekom.de/gardwiki/display/DGHB/X-B3-ParentSpanId"
        required: false
        type: "string"
      responses:
        201:
          description: "Process started"
          schema:
            $ref: "#/definitions/DpuCommissioningResponse"
          headers:
            X-Business-Context:
              type: "string"
              description: "https://gard.telekom.de/gardwiki/display/DGHB/X-Business-Context"
        400:
          description: "Bad request"
          headers:
            X-Business-Context:
              type: "string"
              description: "https://gard.telekom.de/gardwiki/display/DGHB/X-Business-Context"
        500:
          description: "Can't perform operation"
          headers:
            X-Business-Context:
              type: "string"
              description: "https://gard.telekom.de/gardwiki/display/DGHB/X-Business-Context"
  /api/dpucommissioning/v1/dpu/process/{processId}/restore:
    post:
      tags:
      - "DPU Commissioning"
      summary: "Restore a DpuCommissioning process with given processId."
      description: "Restore a DpuCommissioning process with given processId. See DIGIHUB-69366."
      operationId: "restoreProcess"
      parameters:
      - name: "processId"
        in: "path"
        description: "Process instance id"
        required: true
        type: "string"
      - name: "X-Business-Context"
        in: "header"
        description: "https://gard.telekom.de/gardwiki/display/DGHB/X-Business-Context"
        required: false
        type: "string"
      - name: "X-Callback-Correlation-Id"
        in: "header"
        description: "UUID V4 generated identifier. Needs to be unique for each request\
          \ overall all systems. With this the callback URL is identified internally.\
          \ If not provided in request it will be generated by the integration layer\
          \ and will be returned in response. The asynchronous callback will provide\
          \ this ID for correlation of request and callback. "
        required: false
        type: "string"
      responses:
        200:
          description: "OK"
          headers:
            X-Business-Context:
              type: "string"
              description: "https://gard.telekom.de/gardwiki/display/DGHB/X-Business-Context"
        400:
          description: "Bad request"
          headers:
            X-Business-Context:
              type: "string"
              description: "https://gard.telekom.de/gardwiki/display/DGHB/X-Business-Context"
        404:
          description: "Not Found"
          headers:
            X-Business-Context:
              type: "string"
              description: "https://gard.telekom.de/gardwiki/display/DGHB/X-Business-Context"
        500:
          description: "Internal Server Error"
          headers:
            X-Business-Context:
              type: "string"
              description: "https://gard.telekom.de/gardwiki/display/DGHB/X-Business-Context"
definitions:
  DpuCommissioningResponse:
    type: "object"
    properties:
      id:
        type: "string"
        example: "2c77cc8b-53a8-4afd-9d7a-e6557941bb11"
        description: "Process ID"
      source:
        type: "string"
        example: "dpu-commissioning"
        description: "Source"
      businessKey:
        type: "string"
        example: "/dpu-commissioning/2c77cc8b-53a8-4afd-9d7a-e6557941bb11"
        description: "ETCD businessKey"
      index:
        type: "integer"
        format: "int32"
        example: 123
        description: "ETCD index"
    description: "DpuCommissioningResponse"
  StartDpuCommissioningRequest:
    type: "object"
    required:
    - "endSZ"
    properties:
      endSZ:
        type: "string"
        example: "49/8571/0/74GA"
        description: "Endstellenschluesselzahl"
        pattern: "[0-9]{1,6}\\/[0-9]{1,6}\\/[0-9]{1,6}\\/[a-zA-Z0-9]{2,4}"
  StartDpuDecommissioningRequest:
    type: "object"
    required:
    - "endSZ"
    properties:
      endSZ:
        type: "string"
        example: "49/8571/0/74GA"
        description: "Endstellenschluesselzahl"
        pattern: "[0-9]{1,6}\\/[0-9]{1,6}\\/[0-9]{1,6}\\/[a-zA-Z0-9]{2,4}"
