---
swagger: "2.0"
info:
  description: "## Access Process management API"
  version: "1.4.0"
  title: "Access Process management"
host: "localhost:8092"
tags:
  - name: "Process Management Controller"
schemes:
  - "http"
paths:
  /api/processManagement/v1/search:
    post:
      tags:
        - "Process Management Controller"
      summary: "Gets Process by requestProcessInformationDto and managementUIPage."
      description: "Gets Processes by input parameters for search and with additional\
        \ sort parameters."
      operationId: "search"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "apm-principal-token"
          in: "header"
          description: "APM Token"
          required: false
          type: "string"
        - in: "body"
          name: "body"
          description: "Request ProcessInformationDto"
          required: false
          schema:
            $ref: "#/definitions/ProcessInformationDto"
        - name: "direction"
          in: "query"
          description: "direction"
          required: false
          type: "string"
          enum:
            - "ASC"
            - "DESC"
        - name: "page"
          in: "query"
          description: "page"
          required: false
          type: "integer"
          format: "int32"
        - name: "pageSize"
          in: "query"
          description: "pageSize"
          required: false
          type: "integer"
          format: "int32"
        - name: "sortField"
          in: "query"
          description: "sortField"
          required: false
          type: "string"
          enum:
            - "PROCESS_ID"
            - "PROCESS_DEFINITION"
            - "START_TIME"
            - "END_TIME"
            - "PROCESS_STATUS"
      responses:
        200:
          description: "Successfully found"
          schema:
            $ref: "#/definitions/PageProcessInformationViewDto"
        400:
          description: "Can't perform operation"
          schema:
            $ref: "#/definitions/ProblemDetails"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/ProblemDetails"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/ProblemDetails"
        404:
          description: "Not present in database"
          schema:
            $ref: "#/definitions/ProblemDetails"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/ProblemDetails"
  /api/processManagement/v1/{processId}/restore:
    post:
      tags:
        - "Process Management Controller"
      summary: "Restores failed process"
      description: "Restores failed process"
      operationId: "restore"
      parameters:
        - name: "apm-principal-token"
          in: "header"
          description: "APM Token"
          required: false
          type: "string"
        - name: "processId"
          in: "path"
          description: "Process instance id"
          required: true
          type: "string"
          format: "uuid"
      responses:
        200:
          description: "Process restoration started"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ProblemDetails"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/ProblemDetails"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/ProblemDetails"
        404:
          description: "Process instance not found"
          schema:
            $ref: "#/definitions/ProblemDetails"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/ProblemDetails"
definitions:
  Page:
    type: "object"
    properties:
      totalElements:
        type: "integer"
        format: "int64"
      totalPages:
        type: "integer"
        format: "int32"
      size:
        type: "integer"
        format: "int32"
      content:
        type: "array"
        items:
          type: "object"
      number:
        type: "integer"
        format: "int32"
      sort:
        $ref: "#/definitions/Sort"
      first:
        type: "boolean"
      pageable:
        $ref: "#/definitions/Pageable"
      last:
        type: "boolean"
      numberOfElements:
        type: "integer"
        format: "int32"
      empty:
        type: "boolean"
  PageProcessInformationViewDto:
    type: "object"
    properties:
      totalElements:
        type: "integer"
        format: "int64"
      totalPages:
        type: "integer"
        format: "int32"
      size:
        type: "integer"
        format: "int32"
      content:
        type: "array"
        items:
          $ref: "#/definitions/ProcessInformationViewDto"
      number:
        type: "integer"
        format: "int32"
      sort:
        $ref: "#/definitions/Sort"
      first:
        type: "boolean"
      pageable:
        $ref: "#/definitions/Pageable"
      last:
        type: "boolean"
      numberOfElements:
        type: "integer"
        format: "int32"
      empty:
        type: "boolean"
  Pageable:
    type: "object"
    properties:
      offset:
        type: "integer"
        format: "int64"
      sort:
        $ref: "#/definitions/Sort"
      pageSize:
        type: "integer"
        format: "int32"
      paged:
        type: "boolean"
      unpaged:
        type: "boolean"
      pageNumber:
        type: "integer"
        format: "int32"
  ProblemDetails:
    type: "object"
    required:
      - "title"
      - "type"
    properties:
      type:
        type: "string"
        format: "uri"
        description: "type"
      title:
        type: "string"
        description: "title"
      status:
        type: "integer"
        format: "int32"
        description: "status"
      detail:
        type: "string"
        description: "detail"
      instance:
        type: "string"
        description: "instance"
      embedded:
        description: "embedded"
        $ref: "#/definitions/SpecificProblemDetails"
    description: "Error response of 4xx and 5xx http statuses."
  ProcessInformationDto:
    type: "object"
    properties:
      endSz:
        type: "string"
        pattern: "[0-9]{1,6}\\/[0-9]{1,6}\\/[0-9]{1,6}\\/[a-zA-Z0-9]{2,4}"
      slotNumber:
        type: "string"
      portNumber:
        type: "string"
      processId:
        type: "string"
        format: "uuid"
      processState:
        type: "array"
        uniqueItems: true
        items:
          type: "string"
          enum:
            - "RUNNING"
            - "FINISHED"
            - "DELETED"
            - "FAILED"
  ProcessInformationViewDto:
    type: "object"
    properties:
      processInfo:
        type: "string"
      processInstanceId:
        type: "string"
      initProcessInstanceId:
        type: "string"
      startTime:
        type: "string"
        format: "date-time"
      endTime:
        type: "string"
        format: "date-time"
      state:
        type: "string"
        enum:
          - "RUNNING"
          - "FINISHED"
          - "DELETED"
          - "FAILED"
      variables:
        type: "object"
      failedActivityId:
        type: "string"
      failureTime:
        type: "string"
        format: "date-time"
      failureMessage:
        type: "string"
      lastFinishedActivityId:
        type: "string"
      lastFinishedActivityTime:
        type: "string"
        format: "date-time"
  Sort:
    type: "object"
    properties:
      sorted:
        type: "boolean"
      unsorted:
        type: "boolean"
      empty:
        type: "boolean"
  SpecificProblemDetails:
    type: "object"
    required:
      - "code"
      - "reason"
    properties:
      code:
        type: "string"
        description: "code"
      reason:
        type: "string"
        description: "reason"
      message:
        type: "string"
        description: "message"
      status:
        type: "integer"
        format: "int32"
        description: "status"
    description: "Specific problem details(including fehlerbuildnummer code)."
