openapi: 3.0.1
info:
  title: Access Process management
  description: '## Access Process management API'
  version: 1.6.0
servers:
  - url: 'http://localhost:8092/'
tags:
  - name: ProcessManagementController
paths:
  '/resource-order-resource-inventory/v1/processManagement/manualProcessRestoreTask/{processId}':
    post:
      tags:
        - ProcessManagementController
      summary: Restores failed process
      description: Restores failed process
      operationId: restore
      security:
        - apmToken: []
        - OAuth2:
            - 'rori:process:write'
            - 'giga:cga:all-area-access'
      parameters:
        - $ref: '#/components/parameters/ApmToken'
        - $ref: '#/components/parameters/ProcessId'
      responses:
        '200':
          description: Process restoration started
          content: {}
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '401':
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Process instance not found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal server error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /resource-order-resource-inventory/v1/processManagement/searchChildProcesses:
    post:
      tags:
        - ProcessManagementController
      summary: Searches child processes by process ID
      description: Searches child processes by process ID. Also searches tasks of current process
      operationId: searchChildProcesses
      security:
        - apmToken: []
        - OAuth2:
            - 'rori:process:read'
            - 'giga:cga:all-area-access'
      parameters:
        - $ref: '#/components/parameters/ApmToken'
      requestBody:
        description: RequestChildProcessesDto
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestChildProcessesDto'
        required: false
      responses:
        '200':
          description: Successfully found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProcessInformationViewDto'
        '400':
          description: Can't perform operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not present in database
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /resource-order-resource-inventory/v1/processManagement/searchProcessesByParams:
    post:
      tags:
        - ProcessManagementController
      summary: Gets Process by requestProcessInformationDto and managementUIPage.
      description: Gets Processes by input parameters for search and with additional sort parameters.
      operationId: searchProcessesByParams
      security:
        - apmToken: []
        - OAuth2:
            - 'rori:process:read'
            - 'giga:cga:all-area-access'
      parameters:
        - $ref: '#/components/parameters/ApmToken'
        - $ref: '#/components/parameters/Direction'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PageSize'
        - $ref: '#/components/parameters/SortField'
      requestBody:
        description: RequestProcessesDto
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestProcessesDto'
        required: false
      responses:
        '200':
          description: Successfully found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProcessInformationViewDto'
        '400':
          description: Can't perform operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not present in database
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  securitySchemes:
    apmToken:
      type: apiKey
      in: header
      name: apm-principal-token
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://rhsso-develop.magic.telekom.de/auth/realms/GigabitHub/protocol/openid-connect/token'
          scopes:
            'rori:process:write': Write scope
            'rori:process:read': Read scope
            'giga:cga:all-area-access': General Access Scope
  parameters:
    ProcessId:
      name: processId
      in: path
      description: Process instance id
      required: true
      schema:
        type: string
    ApmToken:
      name: apm-principal-token
      in: header
      description: APM Token
      schema:
        type: string
    Direction:
      name: direction
      in: query
      description: direction
      schema:
        $ref: '#/components/schemas/Direction'
    Page:
      name: page
      in: query
      description: page
      schema:
        type: integer
        format: int32
    PageSize:
      name: pageSize
      in: query
      description: pageSize
      schema:
        type: integer
        format: int32
        maximum: 500
    SortField:
      name: sortField
      in: query
      description: sortField
      schema:
        $ref: '#/components/schemas/SearchSortField'
  schemas:
    SearchSortField:
      type: string
      enum:
        - START_TIME
        - END_TIME
        - PROCESS_STATUS
    Direction:
      type: string
      enum:
        - ASC
        - DESC
    ProblemDetails:
      required:
        - title
        - type
      type: object
      properties:
        type:
          type: string
          description: type
        title:
          type: string
          description: title
        status:
          type: integer
          description: status
          format: int32
        detail:
          type: string
          description: detail
        instance:
          type: string
          description: instance
        embedded:
          $ref: '#/components/schemas/SpecificProblemDetails'
      description: Error response of 4xx and 5xx http statuses.
    ProcessInformationViewDto:
      type: object
      properties:
        eventInfo:
          type: string
          description: Information or process definition of the process
        processInstanceId:
          type: string
          description: Unique Process Id of the process
        eventType:
          type: string
          description: Type of event. Can be TASK or PROCESS
          enum:
            - TASK
            - PROCESS
        activityType:
          type: string
          description: Type of the activity
        startTime:
          type: string
          description: Process starting time
          format: date-time
        endTime:
          type: string
          description: Process ending time
          format: date-time
        processState:
          type: string
          description: 'State of the process. Can be RUNNING, FINISHED, DELETED and FAILED'
        variables:
          type: object
          properties: {}
          description: ' Process variables'
        errorMessage:
          type: string
          description: Failure message
        businessKey:
          type: string
          description: Business key of a process
        incidentStatus:
          type: string
          description: 'Status of the incident. Can be OPEN, RESOLVED and DELETED'
          enum:
            - OPEN
            - RESOLVED
            - DELETED
        duration:
          type: string
          description: Duration of a process
    RequestChildProcessesDto:
      required:
        - processInstanceId
      type: object
      properties:
        processInstanceId:
          type: string
          format: uuid
    RequestProcessesDto:
      type: object
      properties:
        endSz:
          pattern: '[0-9]{1,6}\/[0-9]{1,6}\/[0-9]{1,6}\/[a-zA-Z0-9]{2,4}'
          type: string
        slotNumber:
          type: string
        portNumber:
          type: string
        processInstanceId:
          type: string
        processState:
          uniqueItems: true
          type: array
          items:
            type: string
            enum:
              - RUNNING
              - FINISHED
              - DELETED
              - FAILED
    SpecificProblemDetails:
      required:
        - code
        - reason
      type: object
      properties:
        code:
          type: string
          description: code
        reason:
          type: string
          description: reason
        message:
          type: string
          description: message
        status:
          type: integer
          description: status
          format: int32
      description: Specific problem details(including fehlerbuildnummer code).