openapi: 3.0.1
info:
  title: PSL Transformer
  description: '## PSL Transformer API'
  version: 1.1.0
servers:
  - url: http://localhost:8177/
tags:
  - name: PslCallback
  - name: Request
    description: the psl API
paths:
  /api/pslTransformer/v1/callback:
    post:
      security:
        - OAuth2:
            - giga:callback:full
            - giga:cga:all-area-access
      tags:
        - PslCallback
      summary: Callback for SI_ReadEquipmentRequestOutService. This endpoint will be used by SOABP only.
      operationId: callbackFromPsl
      requestBody:
        description: Read equipment response
        content:
          text/xml;charset=UTF-8:
            schema:
              type: string
        required: false
      responses:
        200:
          description: PSL request is processed
          content:
            text/xml;charset=UTF-8:
              schema:
                type: string
        400:
          description: Bad Request (Sync Response on POST Request)
          content: {}
      x-codegen-request-body-name: body
  /resource-order-resource-inventory/v1/psl/read-equipment/:
    post:
      security:
        - OAuth2:
            - rori:pslequipment:full
            - giga:cga:all-area-access
      tags:
        - Request
      operationId: readEquipmentRequest
      parameters:
        - $ref: '#/components/parameters/X-Callback-Id'
        - $ref: '#/components/parameters/X-Callback-Correlation-Id'
        - $ref: '#/components/parameters/X-Callback-Url'
        - $ref: '#/components/parameters/X-Callback-Method'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReadEquipmentRequest'
        required: true
      responses:
        202:
          description: request accepted
          content: {}
        400:
          description: Bad Request (Sync Response on POST Request)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      x-codegen-request-body-name: body
      callbacks:
        callbackReadEquipmentRequest:
          $ref: '#/components/callbacks/callbackReadEquipmentRequest'

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://example.org/token # Just leave this. It is mandatory but not used by our implementation
          scopes:
            'rori:pslequipment:full': PSL Equipment Full Scope
            'giga:callback:full': Callback Scope
            'giga:cga:all-area-access': General Access Scope
  schemas:
    ErrorResponse:
      type: object
      properties:
        errorCode:
          type: string
          description: Error code
        message:
          type: string
          description: Message
      description: Error response of 4xx and 5xx http statuses
    Header:
      required:
        - anfoKen
        - partner
      type: object
      properties:
        partner:
          maxLength: 40
          minLength: 0
          type: string
          default: BS_DIGIOSS
        anfoKen:
          maxLength: 20
          minLength: 0
          type: string
    MessageContext:
      type: object
      properties:
        target:
          maxLength: 64
          minLength: 1
          type: string
        sender:
          maxLength: 255
          minLength: 2
          type: string
        correlationId:
          maxLength: 255
          minLength: 5
          type: string
        redelivered:
          type: string
        replyTo:
          type: string
        requestId:
          maxLength: 255
          minLength: 5
          type: string
        revision:
          type: string
        sequenceId:
          type: string
        timeLeft:
          type: string
        priority:
          type: integer
          format: int32
    ReadEquipmentRequest:
      required:
        - requestData
      type: object
      properties:
        messageContext:
          $ref: '#/components/schemas/MessageContext'
        requestData:
          $ref: '#/components/schemas/ReadEquipmentRequestData'
    ReadEquipmentRequestData:
      required:
        - requestEquipment
      type: object
      properties:
        header:
          $ref: '#/components/schemas/Header'
        requestEquipment:
          type: array
          items:
            $ref: '#/components/schemas/RequestEquipment'
    RequestEquipment:
      required:
        - endsz
      type: object
      properties:
        endsz:
          maxLength: 30
          minLength: 0
          type: string
    ReadEquipmentResponse:
      type: object
      properties:
        messageContext:
          $ref: '#/components/schemas/MessageContext'
        responseData:
          $ref: '#/components/schemas/ReadEquipmentResponseData'
    ReadEquipmentResponseData:
      type: object
      properties:
        header:
          $ref: '#/components/schemas/Header'
        equipment:
          type: array
          items:
            $ref: '#/components/schemas/Equipment'
        status:
          $ref: '#/components/schemas/Status'
    Equipment:
      type: object
      properties:
        equnr:
          maxLength: 18
          type: string
          description: Equipment Number
        tplnr:
          maxLength: 30
          type: string
          description: Technischer Platz
        feld:
          maxLength: 4
          type: string
          description: ""
        ebpl:
          maxLength: 4
          type: string
          description: Einbauplatz
        stpl:
          maxLength: 4
          type: string
          description: Steckplatz
        hequi:
          maxLength: 18
          type: string
          description: Uebergeordnetes Equipment
        heqnr:
          maxLength: 4
          type: string
          description: Position des Equipments
        heUeb:
          maxLength: 1
          type: string
          description: HE-Ueberlauf
        submt:
          maxLength: 18
          type: string
          description: Material Nr.
        ktextMat:
          maxLength: 40
          type: string
          description: Material-Kurztext
        herst:
          maxLength: 10
          type: string
          description: Hersteller Nr.
        herstName:
          maxLength: 10
          type: string
          description: Hersteller Name (kurz)
        fsachnr:
          maxLength: 30
          type: string
          description: Herstellerteile Nr.
        ansdat:
          maxLength: 10
          type: string
          description: Anschaffungsdatum
        eqart:
          maxLength: 1
          type: string
          description: Equipmentart
        endsz:
          maxLength: 30
          type: string
          description: Endstellenschluesselzahl
        ossNodeId:
          maxLength: 30
          type: string
          description: ""
        eqtyp:
          maxLength: 1
          type: string
          description: Equipmenttyp
        objart:
          maxLength: 10
          type: string
          description: Objektart
        anlkl:
          maxLength: 8
          type: string
          description: Anlagenklasse
        debitor:
          maxLength: 10
          type: string
          description: Kunde
        kund3:
          maxLength: 10
          type: string
          description: Betreiber
        invnr:
          maxLength: 25
          type: string
          description: Inventar Nr.
        liznr:
          maxLength: 20
          type: string
          description: Vertrags Nr.
        serge:
          maxLength: 30
          type: string
          description: Serien Nr. des Herstellers vom Geraet
        gerstd:
          maxLength: 16
          type: string
          description: Geraetestand
        aenstd:
          maxLength: 3
          type: string
          description: Aenderungsstand
        swstd:
          maxLength: 5
          type: string
          description: Softwarestand
        awstat:
          maxLength: 4
          type: string
          description: Anwenderstatus
        zawstat:
          maxLength: 4
          type: string
          description: Zusaetzlicher Anwenderstatus
        aktion:
          maxLength: 4
          type: string
          description: Bearbeitungsaktion
        dienstekennung:
          maxLength: 2
          type: string
          description: Zusaetzlicher Anwenderstatus
        hostname:
          maxLength: 30
          type: string
          description: Zusaetzlicher Anwenderstatus
        planungsgeraetename:
          maxLength: 30
          type: string
          description: Zusaetzlicher Anwenderstatus
        gesamtstruktur:
          maxLength: 50
          type: string
          description: Zusaetzlicher Anwenderstatus
        anzEbenen:
          maxLength: 1
          type: string
          description: Zusaetzlicher Anwenderstatus
        bgtEquiNr:
          maxLength: 18
          type: string
          description: Zusaetzlicher Anwenderstatus
        deltastruktur:
          maxLength: 50
          type: string
          description: Zusaetzlicher Anwenderstatus
        datumInvBest:
          maxLength: 10
          type: string
          description: Datum zur letzten Bestaetigung des Vorhan-denseins aus Inventursicht
        ersatzteilkennz:
          maxLength: 1
          type: string
          description: Zusaetzlicher Anwenderstatus
        zmBetrDat:
          maxLength: 1
          type: string
          description: Pflege Betriebl. Daten
        zmStatus:
          maxLength: 1
          type: string
          description: Status Materialreferenzierung
        zmScanrel:
          maxLength: 1
          type: string
          description: Scanrelevant
        vpsz:
          maxLength: 20
          type: string
          description: Verbindungspunktschluesselzahl
        starId:
          maxLength: 12
          type: string
          description: KLS–Lokations–ID zum Objekt VPSZ
        adrId:
          maxLength: 12
          type: string
          description: KLS–Grundstuecks–ID
        nkz:
          maxLength: 6
          type: string
          description: Netzkennzahl
        vpz:
          maxLength: 6
          type: string
          description: Verbindungspunkt
        geba:
          maxLength: 3
          type: string
          description: Gebaeude
        raum:
          maxLength: 3
          type: string
          description: Raum
        reihe:
          maxLength: 3
          type: string
          description: ""
        platz:
          maxLength: 3
          type: string
          description: ""
        asb:
          maxLength: 4
          type: string
          description: Anschlussbereich
        kvz:
          maxLength: 6
          type: string
          description: Schaltpunkt Nr. bei THS–TPL
        spkt:
          maxLength: 7
          type: string
          description: Schaltpunkt Nr. bei THS–TPL
        iwerk:
          maxLength: 4
          type: string
          description: IH–Planungswerk
        ingrp:
          maxLength: 3
          type: string
          description: H–Planergruppe
        fltyp:
          maxLength: 1
          type: string
          description: Typ des Technischen Platzes
        aufnr:
          maxLength: 12
          type: string
          description: SM–Auftragsnummer
        solldat:
          maxLength: 10
          type: string
          description: Aufbaudatum SOLL vom SM–Auftrag (JJJJMMTT)
        bertdat:
          maxLength: 10
          type: string
          description: Datum Anlage Betriebsbereit (JJJJMMTT)
        kostl:
          maxLength: 10
          type: string
          description: Kostenstelle
        ktextSm:
          maxLength: 40
          type: string
          description: Kurztext SM–Auftrag
        pdhnr:
          maxLength: 11
          type: string
          description: Materialbereichs
        bezMb:
          maxLength: 20
          type: string
          description: Bezeichnung
        lkr:
          maxLength: 10
          type: string
          description: Leistungskriterium
        anzLkr:
          maxLength: 7
          type: string
          description: Leistungskriterien
        anlRel:
          maxLength: 1
          type: string
          description: Anlagen-Relevanz
        permInvRel:
          maxLength: 1
          type: string
          description: Mat. Nr. ist Permanent–Inventurrel
        inventarnrRel:
          maxLength: 1
          type: string
          description: X wenn zum Material eine Inventarnummer benoetigt wird
        sernrRel:
          maxLength: 1
          type: string
          description: X wenn zum Material eine Hersteller Seriennummer benoetigt
            wird
    Status:
      type: object
      properties:
        type:
          maxLength: 1
          type: string
        id:
          maxLength: 20
          type: string
        number:
          maxLength: 3
          type: string
        message:
          maxLength: 220
          type: string
        logNo:
          maxLength: 20
          type: string
        logMsgNo:
          maxLength: 6
          type: string
        messageV1:
          maxLength: 50
          type: string
        messageV2:
          maxLength: 50
          type: string
        messageV3:
          type: string
        messageV4:
          maxLength: 50
          type: string
        parameter:
          maxLength: 32
          type: string
        row:
          maxLength: 10
          type: string
        field:
          maxLength: 30
          type: string
        system:
          maxLength: 10
          type: string

  parameters:
    X-Callback-Id:
      name: X-Callback-Id
      in: header
      description: Unique consumerID used to identify the request consumer within
        FUSE and provide support for maintenance
      required: true
      schema:
        type: string
    X-Callback-Url:
      name: X-Callback-Url
      in: header
      description: The provided REST-interface from the consumer where the expected
        callback is sent to
      required: true
      schema:
        type: string
    X-Callback-Method:
      name: X-Callback-Method
      in: header
      description: HTTP method which is used for the callback
      schema:
        type: string
        default: POST
        enum:
          - POST
    X-Callback-Correlation-Id:
      name: X-Callback-Correlation-Id
      in: header
      description: Value for identifying a single transaction across multiple services
        up to the backend. Usually set by the originating consumer
      required: true
      schema:
        type: string
        format: uuid
  callbacks:
    callbackReadEquipmentRequest:
      '{$request.header.X-Callback-Url}':
        post:
          summary: callback for readEquipmentRequest
          parameters:
            - name: X-Callback-Correlation-Id
              in: header
              description: Value for identifying a single transaction across multiple services
                up to the backend. Usually set by the originating consumer
              required: true
              schema:
                type: string
                format: uuid
          requestBody:
            description: result of ReadEquipmentRequest
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ReadEquipmentResponse'
            required: true
          responses:
            200:
              description: Equipment data processed
              content: { }
            500:
              description: Internal error
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ErrorResponse'
