---
swagger: "2.0"
info:
  description: "## RI-Abstraction-Layer API"
  version: "1.2.0"
  title: "RI-Abstraction-Layer"
host: "localhost:8070"
tags:
- name: "DeviceInternalController"
schemes:
- "http"
paths:
  /api/riAbstractionLayer/v1/olt/:
    get:
      tags:
      - "DeviceInternalController"
      summary: "Gets Device by EndSz"
      description: ""
      operationId: "getOltByEndSZ"
      produces:
      - "application/json"
      parameters:
      - name: "apm-principal-token"
        in: "header"
        description: "APM Token"
        required: false
        type: "string"
      - name: "endSz"
        in: "query"
        description: "endSz"
        required: true
        type: "string"
        pattern: "[0-9]{1,6}\\/[0-9]{1,6}\\/[0-9]{1,6}\\/[a-zA-Z0-9]{2,4}"
      responses:
        200:
          description: "Successfully found"
          schema:
            $ref: "#/definitions/Device"
        400:
          description: "Can't perform operation"
          schema:
            $ref: "#/definitions/ProblemDetails"
        404:
          description: "Not present in database"
          schema:
            $ref: "#/definitions/ProblemDetails"
        500:
          description: "Service unavailable"
          schema:
            $ref: "#/definitions/ProblemDetails"
  /api/riAbstractionLayer/v1/olt/vpszlookup:
    get:
      tags:
      - "DeviceInternalController"
      summary: "Returns all endSz's based on the deviceType and vpSz based on endSz\
        \ like% search."
      description: ""
      operationId: "getOltsByEndSzSegment"
      produces:
      - "application/json"
      parameters:
      - name: "apm-principal-token"
        in: "header"
        description: "APM Token"
        required: false
        type: "string"
      - name: "vpsz"
        in: "query"
        description: " Part of Endsz"
        required: true
        type: "string"
        pattern: "^[0-9]{1,6}\\/[0-9]{1,6}\\/[0-9]{1,6}[\\/a-zA-Z0-9]{0,4}"
      - name: "devicetype"
        in: "query"
        description: "Type of element"
        required: true
        type: "string"
        enum:
        - "OLT"
        - "BNG"
      responses:
        200:
          description: "Successfully found"
          schema:
            type: "array"
            items:
              type: "string"
        400:
          description: "Can't perform operation"
          schema:
            $ref: "#/definitions/ProblemDetails"
        502:
          description: "Can't create list from RIs"
          schema:
            $ref: "#/definitions/ProblemDetails"
definitions:
  Card:
    type: "object"
    properties:
      shortName:
        type: "string"
      materialNumber:
        type: "string"
      emsNbiName:
        type: "string"
      tkz1:
        type: "string"
      tkz2:
        type: "string"
      descriptionUrl:
        type: "string"
      lastDiscovery:
        type: "string"
        format: "date-time"
      id:
        type: "integer"
        format: "int64"
      resourceId:
        type: "string"
      name:
        type: "string"
      description:
        type: "string"
      serialNumber:
        type: "string"
      serviceState:
        type: "string"
      resourceState:
        type: "string"
      firmwareVersion:
        type: "string"
      cardType:
        type: "string"
        enum:
        - "GPON"
        - "UPLINK_CARD"
        - "MANAGEMENT_CARD"
        - "SUPPORT_MODULE"
        - "PROCESSING_BOARD"
      equipmentNumber:
        type: "string"
      manufacturer:
        type: "string"
      ports:
        type: "array"
        items:
          $ref: "#/definitions/Port"
      compositePartyId:
        type: "integer"
        format: "int64"
  Device:
    type: "object"
    properties:
      shortName:
        type: "string"
      materialNumber:
        type: "string"
      emsNbiName:
        type: "string"
      tkz1:
        type: "string"
      tkz2:
        type: "string"
      descriptionUrl:
        type: "string"
      lastDiscovery:
        type: "string"
        format: "date-time"
      id:
        type: "integer"
        format: "int64"
      resourceId:
        type: "string"
      deviceName:
        type: "string"
      endSz:
        type: "string"
      fachSz:
        type: "string"
      klsId:
        type: "integer"
        format: "int64"
      ipAddress:
        type: "string"
      firmwareVersion:
        type: "string"
      resourceState:
        type: "string"
        enum:
        - "NON_WORKING"
        - "WORKING"
      communicationState:
        type: "string"
        enum:
        - "AVAILABLE"
        - "UNAVAILABLE"
      serialNumber:
        type: "string"
      importState:
        type: "string"
        enum:
        - "PLANNED"
        - "DISCOVERED"
      type:
        type: "string"
        enum:
        - "OLT"
        - "BNG"
        - "DPU"
      importDate:
        type: "string"
        format: "date-time"
      equipmentHolders:
        type: "array"
        items:
          $ref: "#/definitions/EquipmentHolder"
      description:
        type: "string"
      asb:
        type: "integer"
        format: "int64"
      technicalLocation:
        type: "string"
      equipmentNumber:
        type: "string"
      manufacturer:
        type: "string"
      distributionPointId:
        type: "string"
      lifeCycleState:
        type: "string"
        enum:
        - "NOT_OPERATING"
        - "INSTALLING"
        - "OPERATING"
        - "RETIRING"
        - "PLANNING"
      fiberOnLocationId:
        type: "string"
      ports:
        type: "array"
        items:
          $ref: "#/definitions/Port"
      compositePartyId:
        type: "integer"
        format: "int64"
  EquipmentHolder:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      slotNumber:
        type: "string"
      card:
        $ref: "#/definitions/Card"
  OpticalModule:
    type: "object"
    properties:
      shortName:
        type: "string"
      materialNumber:
        type: "string"
      emsNbiName:
        type: "string"
      tkz1:
        type: "string"
      tkz2:
        type: "string"
      descriptionUrl:
        type: "string"
      lastDiscovery:
        type: "string"
        format: "date-time"
      id:
        type: "integer"
        format: "int64"
      resourceId:
        type: "string"
      name:
        type: "string"
      description:
        type: "string"
      manufacturer:
        type: "string"
      compositePartyId:
        type: "integer"
        format: "int64"
  Port:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      resourceId:
        type: "string"
      lifeCycleState:
        type: "string"
        enum:
        - "NOT_OPERATING"
        - "INSTALLING"
        - "OPERATING"
        - "RETIRING"
        - "PLANNING"
      portType:
        type: "string"
        enum:
        - "PON"
        - "ETHERNET"
        - "GFAST"
      portNumber:
        type: "string"
      opticalModule:
        $ref: "#/definitions/OpticalModule"
      compositePartyId:
        type: "integer"
        format: "int64"
  ProblemDetails:
    type: "object"
    required:
    - "title"
    - "type"
    properties:
      type:
        type: "string"
        description: "type"
      title:
        type: "string"
        description: "title"
      status:
        type: "integer"
        format: "int32"
        description: "status"
      detail:
        type: "string"
        description: "detail"
      instance:
        type: "string"
        description: "instance"
      embedded:
        description: "embedded"
        $ref: "#/definitions/SpecificProblemDetails"
    description: "Error response of 4xx and 5xx http statuses."
  SpecificProblemDetails:
    type: "object"
    required:
    - "code"
    - "reason"
    properties:
      code:
        type: "string"
        description: "code"
      reason:
        type: "string"
        description: "reason"
      message:
        type: "string"
        description: "message"
      status:
        type: "integer"
        format: "int32"
        description: "status"
    description: "Specific problem details(including fehlerbuildnummer code)."
