openapi: 3.0.1
info:
  title: RI-Abstraction-Layer
  description: '## RI-Abstraction-Layer API'
  version: 1.9.0
servers:
  - url: http://localhost:8070/
tags:
  - name: DeviceController
paths:
  /resource-order-resource-inventory/v5/rial/abstractDevice:
    get:
      tags:
        - DeviceController
      summary: Returns OLT or DPU device
      operationId: getDeviceByEndSZ
      security:
        - apmToken: [ ]
        - OAuth2:
            - 'rori:device:read'
            - 'giga:cga:all-area-access'
      parameters:
        - $ref: '#/components/parameters/EndszOpt'
        - $ref: '#/components/parameters/VpszOpt'
        - $ref: '#/components/parameters/SerialNumber'
        - $ref: '#/components/parameters/KlsId'
        - $ref: '#/components/parameters/FiberOnLocationId'
        - name: fields
          in: query
          description: Comma-separated properties to provide in response
          schema:
            type: string
      responses:
        200:
          description: Successfully found
          headers:
            X-Result-Collection-Status:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AbstractDevice'
        400:
          description: Can't perform operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        500:
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /resource-order-resource-inventory/v1/rial/olt/:
    get:
      tags:
        - DeviceController
      summary: Gets Device by EndSz
      operationId: getOltByEndSZ
      security:
        - OAuth2:
            - 'rori:oltDevice:read'
            - 'giga:cga:all-area-access'
      parameters:
        - $ref: '#/components/parameters/Endsz'
      responses:
        200:
          description: Successfully found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        400:
          description: Can't perform operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        404:
          description: Not present in database
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        500:
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /resource-order-resource-inventory/v1/rial/olt/vpszlookup:
    get:
      tags:
        - DeviceController
      summary: Returns all endSz's based on the deviceType and vpSz based on endSz
        like% search.
      operationId: getOltsByEndSzSegment
      security:
        - OAuth2:
            - 'rori:oltDevice:read'
            - 'giga:cga:all-area-access'
      parameters:
        - $ref: '#/components/parameters/Vpsz'
        - $ref: '#/components/parameters/DeviceType'
      responses:
        200:
          description: Successfully found
          headers:
            X-Result-Collection-Status:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        400:
          description: Can't perform operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        500:
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  securitySchemes:
    apmToken:
      type: apiKey
      in: header
      name: apm-principal-token
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://rhsso-develop.magic.telekom.de/auth/realms/GigabitHub/protocol/openid-connect/token'
          scopes:
            'rori:device:read': Read scope
            'rori:oltDevice:read': Read scope
            'giga:cga:all-area-access': General access scope
  parameters:
    EndszOpt:
      name: endSz
      in: query
      description: endSz
      required: false
      schema:
        type: string
    Endsz:
      name: endSz
      in: query
      description: endSz
      required: true
      schema:
        pattern: '[0-9]{1,6}\/[0-9]{1,6}\/[0-9]{1,6}\/[a-zA-Z0-9]{2,4}'
        type: string
    Vpsz:
      name: vpsz
      in: query
      description: 'Part of Endsz'
      required: true
      schema:
        pattern: '^[0-9]{1,6}\/[0-9]{1,6}\/[0-9]{1,6}[\/a-zA-Z0-9]{0,4}'
        type: string
    VpszOpt:
      name: vpsz
      in: query
      description: 'Part of Endsz'
      required: false
      schema:
        pattern: '^[0-9]{1,6}\/[0-9]{1,6}\/[0-9]{1,6}[\/a-zA-Z0-9]{0,4}'
        type: string
    KlsId:
      name: klsId
      in: query
      description: 'KLS ID'
      required: false
      schema:
        type: string
    SerialNumber:
      name: serialNumber
      in: query
      description: 'Serial Number'
      required: false
      schema:
        type: string
    FiberOnLocationId:
      name: fiberOnLocationId
      in: query
      description: 'fiber on location id (folid, unique id), resource which represents the building or rather building-section (distribution-point) where the DPU is'
      required: false
      schema:
        type: string
    DeviceType:
      name: devicetype
      in: query
      description: Type of element
      required: true
      schema:
        type: string
        enum:
          - OLT
          - BNG
  schemas:
    AbstractDevice:
      type: object
      properties:
        id:
          type: integer
          format: int64
        productionPlatform:
          $ref: '#/components/schemas/DeviceProductionPlatform'
        endSz:
          type: string
        fiberOnLocationId:
          type: string
        klsId:
          type: integer
          format: int64
        serialNumber:
          type: string
        emsNbiName:
          type: string
        materialNumber:
          type: string
        accessTransmissionMedium:
          type: string
        lifeCycleState:
          type: string
          enum:
            - NOT_OPERATING
            - INSTALLING
            - OPERATING
            - RETIRING
            - PLANNING
        vpSz:
          type: string
        fSz:
          type: string
        cards:
          type: array
          items:
            $ref: '#/components/schemas/AbstractDeviceCard'
        ports:
          type: array
          items:
            $ref: '#/components/schemas/AbstractDevicePort'
        relatedParty:
          type: object
          description: Related Entity reference. A related party defines party or party role linked to a specific entity.
          required:
            - id
          properties:
            id:
              type: string
              description: unique identifier
    Device:
      type: object
      properties:
        shortName:
          type: string
        materialNumber:
          type: string
        emsNbiName:
          type: string
        tkz1:
          type: string
        tkz2:
          type: string
        descriptionUrl:
          type: string
        lastDiscovery:
          type: string
          format: date-time
        id:
          type: integer
          format: int64
        resourceId:
          type: string
        deviceName:
          type: string
        endSz:
          pattern: '[0-9]{1,6}\/[0-9]{1,6}\/[0-9]{1,6}\/[a-zA-Z0-9]{2,4}'
          type: string
        fachSz:
          pattern: '(76[HZG]|71G)[0-9A-Z]'
          type: string
        klsId:
          type: integer
          format: int64
        ipAddress:
          type: string
        firmwareVersion:
          type: string
        resourceState:
          type: string
          enum:
            - NON_WORKING
            - WORKING
        communicationState:
          type: string
          enum:
            - CS_AVAILABLE
            - CS_UNAVAILABLE
        serialNumber:
          type: string
        importState:
          type: string
          enum:
            - PLANNED
            - DISCOVERED
        type:
          type: string
          enum:
            - OLT
            - BNG
            - DPU
        productionPlatform:
          $ref: '#/components/schemas/DeviceProductionPlatform'
        importDate:
          type: string
          format: date-time
        equipmentHolders:
          type: array
          items:
            $ref: '#/components/schemas/EquipmentHolder'
        description:
          type: string
        asb:
          type: integer
          format: int64
        technicalLocation:
          type: string
        equipmentNumber:
          type: string
        manufacturer:
          type: string
        distributionPointId:
          type: string
        lifeCycleState:
          type: string
          enum:
            - NOT_OPERATING
            - INSTALLING
            - OPERATING
            - RETIRING
            - PLANNING
        fiberOnLocationId:
          pattern: '^\d{0,19}$'
          type: string
        ports:
          type: array
          items:
            $ref: '#/components/schemas/Port'
        creationDate:
          type: string
          format: date-time
        modificationDate:
          type: string
          format: date-time
        compositePartyId:
          type: integer
          format: int64
    AbstractDeviceCard:
      type: object
      properties:
        shortName:
          type: string
        materialNumber:
          type: string
        emsNbiName:
          type: string
        tkz1:
          type: string
        tkz2:
          type: string
        descriptionUrl:
          type: string
        lastDiscovery:
          type: string
          format: date-time
        id:
          type: integer
          format: int64
        resourceId:
          type: string
        name:
          type: string
        description:
          type: string
        serialNumber:
          type: string
        serviceState:
          type: string
        resourceState:
          type: string
        firmwareVersion:
          type: string
        cardType:
          type: string
          enum:
            - GPON
            - UPLINK_CARD
            - MANAGEMENT_CARD
            - SUPPORT_MODULE
            - PROCESSING_BOARD
        equipmentNumber:
          type: string
        manufacturer:
          type: string
        ports:
          type: array
          items:
            $ref: '#/components/schemas/AbstractDevicePort'
        creationDate:
          type: string
          format: date-time
        modificationDate:
          type: string
          format: date-time
        compositePartyId:
          type: integer
          format: int64
    Card:
      type: object
      properties:
        shortName:
          type: string
        materialNumber:
          type: string
        emsNbiName:
          type: string
        tkz1:
          type: string
        tkz2:
          type: string
        descriptionUrl:
          type: string
        lastDiscovery:
          type: string
          format: date-time
        id:
          type: integer
          format: int64
        resourceId:
          type: string
        name:
          type: string
        description:
          type: string
        serialNumber:
          type: string
        serviceState:
          type: string
        resourceState:
          type: string
        firmwareVersion:
          type: string
        cardType:
          type: string
          enum:
            - GPON
            - UPLINK_CARD
            - MANAGEMENT_CARD
            - SUPPORT_MODULE
            - PROCESSING_BOARD
        equipmentNumber:
          type: string
        manufacturer:
          type: string
        ports:
          type: array
          items:
            $ref: '#/components/schemas/Port'
        creationDate:
          type: string
          format: date-time
        modificationDate:
          type: string
          format: date-time
        compositePartyId:
          type: integer
          format: int64
    EquipmentHolder:
      type: object
      properties:
        id:
          type: integer
          format: int64
        slotNumber:
          type: string
        card:
          $ref: '#/components/schemas/Card'
    OpticalModule:
      type: object
      properties:
        shortName:
          type: string
        materialNumber:
          type: string
        emsNbiName:
          type: string
        tkz1:
          type: string
        tkz2:
          type: string
        descriptionUrl:
          type: string
        lastDiscovery:
          type: string
          format: date-time
        id:
          type: integer
          format: int64
        resourceId:
          type: string
        name:
          type: string
        description:
          type: string
        manufacturer:
          type: string
        creationDate:
          type: string
          format: date-time
        modificationDate:
          type: string
          format: date-time
        compositePartyId:
          type: integer
          format: int64
    Port:
      type: object
      properties:
        id:
          type: integer
          format: int64
        resourceId:
          type: string
        lifeCycleState:
          type: string
          enum:
            - NOT_OPERATING
            - INSTALLING
            - OPERATING
            - RETIRING
            - PLANNING
        portType:
          type: string
          enum:
            - PON
            - ETHERNET
            - GFAST
        portNumber:
          type: string
        opticalModule:
          $ref: '#/components/schemas/OpticalModule'
        creationDate:
          type: string
          format: date-time
        modificationDate:
          type: string
          format: date-time
        compositePartyId:
          type: integer
          format: int64
    AbstractDevicePort:
      type: object
      properties:
        id:
          type: integer
          format: int64
        resourceId:
          type: string
        lifeCycleState:
          type: string
          enum:
            - NOT_OPERATING
            - INSTALLING
            - OPERATING
            - RETIRING
            - PLANNING
        portType:
          type: string
        portNumber:
          type: string
        opticalModule:
          $ref: '#/components/schemas/OpticalModule'
        creationDate:
          type: string
          format: date-time
        modificationDate:
          type: string
          format: date-time
        compositePartyId:
          type: integer
          format: int64
    DataCollectionStatus:
      type: string
      description: Collected Data Status
      enum:
        - SUCCESFUL
        - SOME_INVENTORIES_FAILED
        - FAILED
    DeviceProductionPlatform:
      type: string
      description: Production platform
      enum:
        - OLT_BNG
        - A4
    ProblemDetails:
      required:
        - title
        - type
      type: object
      properties:
        type:
          type: string
          description: type
        title:
          type: string
          description: title
        status:
          type: integer
          description: status
          format: int32
        detail:
          type: string
          description: detail
        instance:
          type: string
          description: instance
        embedded:
          $ref: '#/components/schemas/SpecificProblemDetails'
      description: Error response of 4xx and 5xx http statuses.
    SpecificProblemDetails:
      required:
        - code
        - reason
      type: object
      properties:
        code:
          type: string
          description: code
        reason:
          type: string
          description: reason
        message:
          type: string
          description: message
        status:
          type: integer
          description: status
          format: int32
      description: Specific problem details(including fehlerbuildnummer code).