openapi: 3.0.3
info:
  title: A4-Inventory-Importer API
  version: 3.3.0
  description: API for A4 Resource Inventory UI BFF communication
  contact:
    email: DL_Berlinium@telekom.de
#SECURITY--------------------------------------------------------------------------------------------------
security:
  - OAuth2:
      - giga:cga:all-area-access
paths:
  /networkElementLinks/findByVpszAndFsz:
    get:
      security:
        - OAuth2:
            - 'rori:networkElementLinks:full'
            - 'giga:cga:all-area-access'
      tags:
        - NetworkElementLinks
      operationId: findNetworkElementLinksByVpszAndFsz
      description: Find Network Element Links By EndSz
      parameters:
        - name: vpsz
          in: query
          description: VPSZ for filtering the NetworkElementLinks
          required: true
          schema:
            $ref: '#/components/schemas/AllowedCharacters'
        - name: fsz
          in: query
          description: FSZ for filtering the NetworkElementLinks
          required: false
          schema:
            $ref: '#/components/schemas/AllowedCharacters'
      responses:
        "200":
          description: get list of Network Element Links - success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/NetworkElementLink"
        "400":
          description: get list of Network Element Links - Bad Request
        "404":
          description: get list of Network Element Links - Not Found
        "500":
          description: get list of Network Element Links - Internal Server Error
  /networkElementLinks/installation:
    post:
      security:
        - OAuth2:
            - 'rori:networkElementLinks:full'
            - 'giga:cga:all-area-access'
      tags:
        - NetworkElementLinks
      operationId: startNetworkElementLinkInstallation
      description: Start installation of Network Element Links
      requestBody:
        description: list of uuids that should be installed
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
        required: true
      responses:
        "200":
          description: startNetworkElementLinkInstallation - success
        "400":
          description: startNetworkElementLinkInstallation - Bad Request
        "404":
          description: startNetworkElementLinkInstallation - Not Found
        "500":
          description: startNetworkElementLinkInstallation - Internal Server Error
  /networkElements/findByVpsz:
    get:
      security:
        - OAuth2:
            - 'rori:networkElements:get'
            - 'giga:cga:all-area-access'
      tags:
        - NetworkElements
      operationId: findNetworkElementsByVpsz
      description: Find Network Elements by EndSz and Categorie
      parameters:
        - name: vpsz
          in: query
          description: VPSZ for filtering the NetworkElements
          required: true
          schema:
            $ref: '#/components/schemas/AllowedCharacters'
        - name: fsz
          in: query
          description: FSZ for filtering the NetworkElements
          required: false
          schema:
            $ref: '#/components/schemas/AllowedCharacters'
        - name: category
          in: query
          description: Category for filtering the NetworkElements
          required: false
          schema:
            $ref: '#/components/schemas/AllowedCharacters'
        - name: lifecycleState
          in: query
          description: LifecycleState for filtering the NetworkElements
          required: false
          schema:
            $ref: '#/components/schemas/AllowedCharacters'
      responses:
        "200":
          description: get list of NetworkElements - success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/NetworkElement"
        "400":
          description: get list of NetworkElements - Bad Request
        "404":
          description: get list of NetworkElements - Not Found
        "500":
          description: get list of NetworkElements - Internal Server Error
  /networkElements/findByUuid:
    get:
      security:
        - OAuth2:
            - 'rori:networkElements:get'
            - 'giga:cga:all-area-access'
      tags:
        - NetworkElements
      operationId: findNetworkElementsByUuid
      description: Find Network Element in resource inventory by UUID
      parameters:
        - name: uuid
          in: query
          description: UUID of the NetworkElement
          required: true
          schema:
            $ref: '#/components/schemas/AllowedUuidCharacters'
      responses:
        "200":
          description: get Network Element by UUID - success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NetworkElement"
        "400":
          description: get Network Element - Bad Request
        "404":
          description: get Network Element - Not Found
        "500":
          description: Internal Server Error
  /ztpIdent:
    post:
      security:
        - OAuth2:
            - 'rori:ztpIdent:post'
            - 'giga:cga:all-area-access'
      tags:
        - NetworkElements
      operationId: updateNetworkElement
      description: Update Network Element in resource inventory
      parameters:
        - name: uuid
          in: query
          description: UUID of the NetworkElement
          required: true
          schema:
            $ref: '#/components/schemas/AllowedUuidCharacters'
        - name: ztpIdent
          in: query
          description: The ztpIdent/Serialnumber of an NetworkElement
          required: false
          schema:
            $ref: '#/components/schemas/AllowedCharacters'
      responses:
        "200":
          description: post NetworkElement - success
        "400":
          description: post NetworkElement - Bad Request
        "404":
          description: post NetworkElement - Not Found
        "500":
          description: post NetworkElement - Internal Server Error
  /uploadCsvFile:
    post:
      security:
        - OAuth2:
            - 'rori:uploadCsvFile:post'
            - 'giga:cga:all-area-access'
      tags:
        - UploadCsvFile
      operationId: uploadCsvFile
      description: Upload CSV File - max. size 1 Mb or 100 rows
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: Upload CSV File - success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CsvFileUploadResult"
        "400":
          description: Upload CSV File - Bad Request
        "500":
          description: Upload CSV File - Internal Server Error
  /pluralAlignment:
    post:
      security:
        - OAuth2:
            - 'rori:pluralAlignment:post'
            - 'giga:cga:all-area-access'
      tags:
        - PluralAlignment
      operationId: pluralAlignment
      description: Update resource inventory with data from PLURAL
      parameters:
        - name: nameNEG
          in: query
          description: Name of NetworkElementGroup
          required: true
          schema:
            $ref: '#/components/schemas/AllowedCharacters'
      responses:
        "200":
          description: post - success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CsvFileUploadResult"
        "400":
          description: post - Bad Request
        "404":
          description: post - Not Found
        "500":
          description: post - Internal Server Error
components:
  schemas:
    NetworkElementLink:
      type: object
      properties:
        uuid:
          $ref: '#/components/schemas/AllowedUuidCharacters'
        lbz:
          $ref: '#/components/schemas/AllowedCharacters'
        lsz:
          $ref: '#/components/schemas/AllowedCharacters'
        orderNumber:
          $ref: '#/components/schemas/AllowedCharacters'
        pluralId:
          $ref: '#/components/schemas/AllowedCharacters'
        ueWegId:
          $ref: '#/components/schemas/AllowedCharacters'
        lifecycleState:
          $ref: '#/components/schemas/AllowedCharacters'
        operationalState:
          $ref: '#/components/schemas/AllowedCharacters'
        rebellPortLabel:
          $ref: '#/components/schemas/AllowedCharacters'
      description: NetworkElementLink within Access 4.0 project
    CsvFileUploadResult:
      type: object
      title: CsvFileUploadResult
      description: Response CsvFileUploadResult Object
      properties:
        csvLineSize:
          $ref: '#/components/schemas/AllowedCharacters'
        numberCreatedNetworkElementGroups:
          $ref: '#/components/schemas/AllowedCharacters'
        numberCreatedNetworkElements:
          $ref: '#/components/schemas/AllowedCharacters'
        numberCreatedNetworkElementPorts:
          $ref: '#/components/schemas/AllowedCharacters'
        numberUpdatedNetworkElements:
          $ref: '#/components/schemas/AllowedCharacters'
        successLines:
          $ref: '#/components/schemas/AllowedCharacters'
        errorLines:
          $ref: '#/components/schemas/AllowedCharacters'
        numberNemoUpdateTasks:
          $ref: '#/components/schemas/AllowedCharacters'
    NetworkElement:
      title: NetworkElement
      type: object
      properties:
        uuid:
          type: string
          description: UUID of this Network Element item
          pattern: '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}'
        creationTime:
          type: string
          description: Timestamp in UTC when this Network Element item was created.
            Automatically filled when creating a new Network Element item
          format: date-time
        description:
          type: string
          description: attributes of this Network Element item
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        lastUpdateTime:
          type: string
          description: Timestamp in UTC when this Network Element item was last updated.
            Automatically updated when updating a Network Element item
          format: date-time
        specificationVersion:
          type: string
          description: specificationVersion of a Network Element
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        address:
          type: string
          description: Address of this Network Element item
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        administrativeState:
          type: string
          description: Administrative State of this Network Element item. Must contain
            one valid state value
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        fsz:
          type: string
          description: FSZ of this Network Element item. Must be unique in combination
            with VPSZ
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        vpsz:
          type: string
          description: VPSZ of this Network Element item. Must be unique in combination
            with FSZ
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        klsId:
          type: string
          description: KLS-ID of this Network Element item
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        lifecycleState:
          type: string
          description: Lifecycle State of this Network Element item. Must contain
            one valid state value
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        operationalState:
          type: string
          description: Operational State of this Network Element item. Must contain
            one valid state value
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        plannedMatNumber:
          type: string
          description: planned material number of this Network Element item
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        plannedRackId:
          type: string
          description: Planned Rack ID of this Network Element item
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        plannedRackPosition:
          type: string
          description: Planned Rack Position of this Network Element item
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        planningDeviceName:
          type: string
          description: Planning Device Name of this Network Element item
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        roles:
          type: string
          description: Roles of this Network Element item. Must contain one valid
            role value XX
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        type:
          type: string
          description: Type of this Network Element item. Must contain one valid type
            value
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        category:
          type: string
          description: NE-Category for filtering the NetworkElements
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        ztpIdent:
          type: string
          description: ZTP-Ident of this Network Element item
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        networkElementGroupUuid:
          type: string
          description: UUID of Network Element Group item to which this Network Element
            item belongs. Must contain UUID of an existing Network Element Group
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        partyId:
          type: string
          description: Party ID of entity to which network elements belongs to
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        fiberOnLocationId:
          type: string
          description: fiberOnLocationId of this Network Element item
          pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
        href:
          type: string
          description: References to NetworkElementGroup
      description: Network Elements are one of several element types of A4 resources.
        Needed for communication between A4 resource inventory and resource inventory
        service.
    AllowedCharacters:
      title: AllowedCharacters
      pattern: '[\w,/!=§#@€:µ.*+? \-\u00C0-\u017F]*'
      type: string
      description: Validator for AllowedCharacters
    AllowedUuidCharacters:
      title: AllowedUuidCharacters
      pattern: '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}'
      type: string
      description: Validator for AllowedUuidCharacters
    Error:
      type: object
      properties:
        code:
          type: string
          description: the code of the Fehlerbildnummer
        reason:
          type: string
          description: Text that explains the reason for error. This can be shown
            to a client user.
          example: Http Error
        message:
          type: string
          description: Text that provide more details and corrective actions related
            to the error. This can be shown to a client user.
          example: Please check your request
      description: Error model from the TMF OpenAPI
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://rhsso-develop.magic.telekom.de/auth/realms/GigabitHub/protocol/openid-connect/token'
          scopes:
            'giga:cga:all-area-access': General Access Scope
            'rori:networkElements:get': GET Scope
            'rori:ztpIdent:post': POST Scope
            'rori:networkElementLinks:full': Full Scope
