openapi: 3.0.0
info:
  version: 1.2.0
  title: Access Line Management
  description: Access Line Management API
servers:
  - url: http://localhost
tags:
  - name: Access Line
paths:
  /resource-order-resource-inventory/v1/updateAccessLineTask/{accessLineId}:
    patch:
      operationId: updateAccessLine
      tags:
      - Access Line
      summary: Update access line
      description: "API for editing a given access line. Allows to run multiply operations for a single line at once using JSON-Patch (see RFC-6902 for details: https://tools.ietf.org/html/rfc6902)"
      parameters:
      - in: path
        name: accessLineId
        description: Access line ID
        required: true
        schema:
          type: "string"
          format: "string"
          pattern: "[A-Z0-9]{3}\\.[A-Z0-9]{1,6}\\.[A-Z0-9]{1,10}"
      - in: header
        name: apm-principal-token
        description: APM Token
        required: false
        schema:
          type: "string"
          format: "string"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestBodyAccessLine"
      responses:
        200:
          description: Access line has been updated
        400:
          description: Incorrect input parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        404:
          description: The access line has not been found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        409:
          description: The profile is already updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
  /resource-order-resource-inventory/v1/assignOnuIdTask:
    post:
      operationId: assignOnuIdTask
      tags:
      - OnuId Task
      summary: Assign onu id to port
      description: "API for executing assign task for onuId with determined parameters (lineId, dpuEndSz and etc.)"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AssignOnuIdTaskDto"
      responses:
        200:
          description: Successfully executed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OnuIdDto"
        400:
          description: Can't perform operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        500:
          description: Internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
  /resource-order-resource-inventory/v1/releaseOnuIdTask:
    post:
      operationId: releaseOnuIdTask
      tags:
      - OnuId Task
      summary: Release onu id from port
      description: "API for executing release task for onuId with determined parameters (lineId, dpuEndSz and etc.)"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReleaseOnuIdTaskDto"
      responses:
        200:
          description: Successfully executed
        400:
          description: Can't perform operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        500:
          description: Internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
  /resource-order-resource-inventory/v1/createAccessLineTask:
    post:
      operationId: create
      tags:
        - Access Line
      summary: Create access line
      description: "API for creating an access line"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateAccessLineDto"
      responses:
        201:
          description: Successfully executed
        400:
          description: Can't perform operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        500:
          description: Internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
  /resource-order-resource-inventory/v1/nlProfilesDefaults:
    get:
      operationId: nlProfilesDefaults
      tags:
        - NL profiles
      summary: Get default values of NL profiles
      description: "API for getting default values of NL profiles"
      parameters:
        - in: query
          name: technology
          description: Technology
          required: true
          schema:
            type: "string"
            format: "string"
      responses:
        200:
          description: "Successfully find"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultProfilesValuesDto"
        400:
          description: Can't perform operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        500:
          description: Internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
components:
  schemas:
    RequestBodyAccessLine:
      type: array
      description: Body
      items:
        $ref: '#/components/schemas/JsonPatchOperation'
    JsonPatchOperation:
      type: object
      required:
      - op
      - path
      properties:
        op:
          type: string
          enum:
          - "add"
          - "remove"
          - "replace"
        path:
          type: string
        value:
          type: object
    AssignOnuIdTaskDto:
      type: "object"
      required:
      - "oltEndSz"
      - "portNumber"
      properties:
        oltEndSz:
          type: "string"
          description: "EndSz of olt device for assign onuId"
          pattern: "[0-9]{1,6}\\/[0-9]{1,6}\\/[0-9]{1,6}\\/[a-zA-Z0-9]{2,4}"
        slotNumber:
          type: "string"
          description: "SlotNumber of olt device for assign onuId"
        portNumber:
          type: "string"
          description: "PortNumber of olt device for assign onuId"
        dpuEndSz:
          type: "string"
          description: "EndSz of dpu device for assign onuId"
          pattern: "[0-9]{1,6}\\/[0-9]{1,6}\\/[0-9]{1,6}\\/[a-zA-Z0-9]{2,4}"
        lineId:
          type: "string"
          description: "LineId of access line for assign onuId"
          pattern: "[A-Z0-9]{3}\\.[A-Z0-9]{1,6}\\.[A-Z0-9]{1,10}"
    OnuIdDto:
      type: "object"
      properties:
        onuId:
          type: "integer"
          format: "int32"
          description: "integer value of onu id"
    ReleaseOnuIdTaskDto:
      type: "object"
      required:
      - "oltEndSz"
      - "onuId"
      - "portNumber"
      properties:
        oltEndSz:
          type: "string"
          description: "EndSz of olt device to release onuId"
          pattern: "[0-9]{1,6}\\/[0-9]{1,6}\\/[0-9]{1,6}\\/[a-zA-Z0-9]{2,4}"
        slotNumber:
          type: "string"
          description: "SlotNumber of olt device to release onuId"
        portNumber:
          type: "string"
          description: "PortNumber of olt device to release onuId"
        onuId:
          type: "integer"
          format: "int32"
          description: "Integer value of onuId on access line(s) to release onuId"
          minimum: 0
          maximum: 128
    CreateAccessLineDto:
      type: "object"
      required:
        - "oltEndSz"
        - "slotNumber"
        - "portNumber"
        - "lineId"
        - "partyId"
      properties:
        oltEndSz:
          type: "string"
          description: "EndSz of olt device to release onuId"
          pattern: "[0-9]{1,6}\\/[0-9]{1,6}\\/[0-9]{1,6}\\/[a-zA-Z0-9]{2,4}"
        slotNumber:
          type: "string"
          description: "SlotNumber of olt device"
        portNumber:
          type: "string"
          description: "PortNumber of olt device"
        lineId:
          type: "string"
          description: "Line Id"
          pattern: "[A-Z0-9]{3}\\.[A-Z0-9]{1,6}\\.[A-Z0-9]{1,10}"
        partyId:
          type: "integer"
          format: "int32"
          description: "Party id of Access Line"
    ProblemDetails:
      type: "object"
      required:
      - "title"
      - "type"
      properties:
        type:
          type: "string"
          format: "uri"
          description: "type"
        title:
          type: "string"
          description: "title"
        status:
          type: "integer"
          format: "int32"
          description: "status"
        detail:
          type: "string"
          description: "detail"
        instance:
          type: "string"
          description: "instance"
        embedded:
          $ref: "#/components/schemas/SpecificProblemDetails"
      description: "Error response of 4xx and 5xx http statuses."
    SpecificProblemDetails:
      type: "object"
      required:
      - "code"
      - "reason"
      properties:
        code:
          type: "string"
          description: "code"
        reason:
          type: "string"
          description: "reason"
        message:
          type: "string"
          description: "message"
        status:
          type: "integer"
          format: "int32"
          description: "status"
      description: "Specific problem details(including fehlerbuildnummer code)."
    DefaultProfilesValuesDto:
      type: object
      description: default values of NL profiles
      properties:
        subscriberNetworkLineProfileDto:
          $ref: '#/components/schemas/SubscriberNetworkLineProfileDto'
        defaultNetworkLineProfileDto:
          $ref: '#/components/schemas/DefaultNetworkLineProfileDto'
    SubscriberNetworkLineProfileDto:
      type: object
      description: default values of default NL subscriber profile
      properties:
        id:
          type: "integer"
          format: "int64"
          description: "Internal (from database) id of SubscriberNetworkLineProfile\
            \ entity"
        authMethod:
          type: "integer"
          format: "int32"
          description: "Authentication method of SubscriberNetworkLineProfile"
        klsId:
          type: "integer"
          format: "int64"
          description: "KlsId of SubscriberNetworkLineProfile"
        minDownBandwidth:
          type: "integer"
          format: "int32"
          description: "Minimum down bandwidth of SubscriberNetworkLineProfile"
        minUpBandwidth:
          type: "integer"
          format: "int32"
          description: "Minimum up bandwidth of SubscriberNetworkLineProfile"
        guaranteedDownBandwidth:
          type: "integer"
          format: "int32"
          description: "Guaranteed down bandwidth of SubscriberNetworkLineProfile"
        guaranteedUpBandwidth:
          type: "integer"
          format: "int32"
          description: "Guaranteed up bandwidth of SubscriberNetworkLineProfile"
        maxDownBandwidth:
          type: "integer"
          format: "int32"
          description: "Maximum down bandwidth of SubscriberNetworkLineProfile"
        maxUpBandwidth:
          type: "integer"
          format: "int32"
          description: "Maximum up bandwidth of SubscriberNetworkLineProfile"
        downBandwidth:
          type: "integer"
          format: "int32"
          description: "Down bandwidth of SubscriberNetworkLineProfile"
        upBandwidth:
          type: "integer"
          format: "int32"
          description: "Up bandwidth of SubscriberNetworkLineProfile"
        state:
          type: "string"
          description: "State of SubscriberNetworkLineProfile (inactive, active)"
          enum:
            - "INACTIVE"
            - "ACTIVE"
        federationPartner:
          type: "string"
          description: "Federation partner of SubscriberNetworkLineProfile"
        providerId:
          type: "string"
          description: "provider id of SubscriberNetworkLineProfile"
        substitutionDomain:
          type: "string"
          description: "Substitution domain of SubscriberNetworkLineProfile"
        l2ccid:
          type: "string"
          description: "12 ccid of SubscriberNetworkLineProfile"
        version:
          type: "integer"
          format: "int64"
          description: "Version of object"
        syncStatus:
          type: "string"
          description: "Profile sync status"
          enum:
            - "OUT_OF_SYNC"
            - "SYNC_IN_PROGRESS"
            - "SYNC_FAILED"
    DefaultNetworkLineProfileDto:
      type: object
      description: default values of subscriber NL subscriber profile
      properties:
        id:
          type: "integer"
          format: "int64"
          description: "Internal (from database) id of DefaultNetworkLineProfile entity"
        authMethod:
          type: "integer"
          format: "int32"
          description: "Authentication method of DefaultNetworkLineProfile"
        klsId:
          type: "integer"
          format: "int64"
          description: "KlsId of DefaultNetworkLineProfile"
        minDownBandwidth:
          type: "integer"
          format: "int32"
          description: "Minimum down bandwidth of DefaultNetworkLineProfile"
        minUpBandwidth:
          type: "integer"
          format: "int32"
          description: "Minimum up bandwidth of DefaultNetworkLineProfile"
        guaranteedDownBandwidth:
          type: "integer"
          format: "int32"
          description: "Guaranteed down bandwidth of DefaultNetworkLineProfile"
        guaranteedUpBandwidth:
          type: "integer"
          format: "int32"
          description: "Guaranteed up bandwidth of DefaultNetworkLineProfile"
        maxDownBandwidth:
          type: "integer"
          format: "int32"
          description: "Maximum down bandwidth of DefaultNetworkLineProfile"
        maxUpBandwidth:
          type: "integer"
          format: "int32"
          description: "Maximum up bandwidth of DefaultNetworkLineProfile"
        state:
          type: "string"
          description: "State of DefaultNeProfile (inactive, active)"
          enum:
            - "INACTIVE"
            - "ACTIVE"
        federationPartner:
          type: "string"
          description: "Federation partner of DefaultNetworkLineProfile"
        accessNetworkType:
          type: "string"
          description: "Access network type of DefaultNetworkLineProfile"
        accessType:
          type: "string"
          description: "Access type of DefaultNetworkLineProfile"
        version:
          type: "integer"
          format: "int64"
          description: "Version of object"
        syncStatus:
          type: "string"
          description: "Profile sync status"
          enum:
            - "OUT_OF_SYNC"
            - "SYNC_IN_PROGRESS"
            - "SYNC_FAILED"
