---
swagger: "2.0"
info:
  description: "## Home ID Management API\n\nMicroservice to manage home IDs."
  version: "1.2.0"
  title: "Home ID Management"
host: "localhost:8065"
tags:
  - name: "HomeIdManagementExternalController"
schemes:
  - "http"
paths:
  /resource-order-resource-inventory/v1/assignedHomeId:
    put:
      tags:
        - "HomeIdManagementExternalController"
      summary: "Sets HomeId to ASSIGNED"
      description: "Checks status of this home id.\n * If RESERVED - sets it to ASSIGNED.\n\
        \ * If ASSIGNED - leaves it ASSIGNED.\n * If FREE - throw exception."
      operationId: "assignedHomeId"
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "HomeIdDto"
          required: true
          schema:
            $ref: "#/definitions/HomeIdDto"
      responses:
        200:
          description: "HomeId was assigned"
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/ProblemDetails"
        404:
          description: "HomeId not found"
          schema:
            $ref: "#/definitions/ProblemDetails"
        409:
          description: "HomeId is free"
          schema:
            $ref: "#/definitions/ProblemDetails"
        500:
          description: "Internal error"
          schema:
            $ref: "#/definitions/ProblemDetails"
  /resource-order-resource-inventory/v1/freeHomeId:
    put:
      tags:
        - "HomeIdManagementExternalController"
      summary: "Reserves HomeId"
      description: "Sets first free homeID to RESERVED."
      operationId: "freeHomeId"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Port reference"
          required: true
          schema:
            $ref: "#/definitions/PortReferenceDto"
      responses:
        200:
          description: "Successfully get"
          schema:
            $ref: "#/definitions/HomeIdDto"
        400:
          description: "Can't perform operation"
          schema:
            $ref: "#/definitions/ProblemDetails"
        404:
          description: "Reference to physical resource not found"
          schema:
            $ref: "#/definitions/ProblemDetails"
        500:
          description: "Internal error"
          schema:
            $ref: "#/definitions/ProblemDetails"
  /resource-order-resource-inventory/v1/homeIdStatuses:
    put:
      tags:
        - "HomeIdManagementExternalController"
      summary: "Updates particular home id status"
      description: ""
      operationId: "updateHomeId"
      consumes:
        - "application/json"
      parameters:
        - name: "apm-principal-token"
          in: "header"
          description: "APM Token"
          required: false
          type: "string"
        - in: "body"
          name: "body"
          description: "HomeIdWithStatusDto"
          required: true
          schema:
            $ref: "#/definitions/HomeIdWithStatusDto"
      responses:
        200:
          description: "HomeId status was updated"
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/ProblemDetails"
        404:
          description: "HomeId not found"
          schema:
            $ref: "#/definitions/ProblemDetails"
        500:
          description: "Internal error"
          schema:
            $ref: "#/definitions/ProblemDetails"
definitions:
  HomeIdDto:
    type: "object"
    required:
      - "homeId"
    properties:
      homeId:
        type: "string"
        pattern: "^[A-Z0-9]{7}$"
  HomeIdWithStatusDto:
    type: "object"
    required:
      - "homeId"
      - "status"
    properties:
      homeId:
        type: "string"
        pattern: "^[A-Z0-9]{7}$"
      status:
        type: "string"
        enum:
          - "FREE"
          - "RESERVED"
          - "ASSIGNED"
  PortReferenceDto:
    type: "object"
    required:
      - "fachSz"
      - "portNumber"
      - "vpSz"
    properties:
      vpSz:
        type: "string"
        pattern: "[0-9]{1,6}\\/[0-9]{1,6}\\/[0-9]{1,6}"
      fachSz:
        type: "string"
        pattern: "[a-zA-Z0-9]{2,4}"
      slotNumber:
        type: "string"
      portNumber:
        type: "string"
  ProblemDetails:
    type: "object"
    required:
      - "title"
      - "type"
    properties:
      type:
        type: "string"
        description: "type"
      title:
        type: "string"
        description: "title"
      status:
        type: "integer"
        format: "int32"
        description: "status"
      detail:
        type: "string"
        description: "detail"
      instance:
        type: "string"
        description: "instance"
      embedded:
        description: "embedded"
        $ref: "#/definitions/SpecificProblemDetails"
    description: "Error response of 4xx and 5xx http statuses."
  SpecificProblemDetails:
    type: "object"
    required:
      - "code"
      - "reason"
    properties:
      code:
        type: "string"
        description: "code"
      reason:
        type: "string"
        description: "reason"
      message:
        type: "string"
        description: "message"
      status:
        type: "integer"
        format: "int32"
        description: "status"
    description: "Specific problem details(including fehlerbuildnummer code)."
